### ISSUE TITLE
Create Role for Educational Technology in new Learning Space

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#10]
System wide role without Site Administration Capabilty for Learning Technologists. Site Admin will be local and Head of ET only?

**Comment by oscott** [comment]
Head of ET /  Senior LT should have personal accounts with site admin enabled. Super local (stored in Knowledge) this account will still be available for obvious reasons, but site admin changes, should go through ETCM ( ~~canoe~~ change management)
[@themarkness @oscott @patrick-et]

**Comment by themarkness** [comment]
Role created as duplicate of teacher and role assigned to team. Role capabilities need reviewing.
