### ISSUE TITLE
Amend Academic Role

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#102]
Academic Role needs to be amended to take some of the settings out. Will document on here and post cm request it.

**Comment by oscott** [comment]
@damienh I thought the plan was to decide what blocks needs showing rather than showing all blocks? Through staff permissions anyhooo ?

**Comment by Asampson** [comment]
This is what I'm proposing to set to not allow:

Configure restore options
Restore activities
Restore courses
Restore sections
Restore from files targeted as hub
Restore from files targeted as import
Upload files to backup areas
Configure cohort instances using Cohort Sync (not even sure we're using this!)
Manage local filter settings
Reset course
Backup for import

**Comment by damienh** [comment]
@oscott this is a seperate block in the settings block. I believe its different for settings for the SMSBlock for example

**Comment by themarkness** [comment]
All looks good to me @Asampson

**Comment by oscott** [comment]
@Asampson all looks good to me. Gofer it.

@damienh I think the conversation I was having here was more along the lines of blocks in general - did you do any work on allowing / disallowing certain blocks for staff / students?

**Comment by Asampson** [comment]
Also set to not allow:
Backup courses
Configure backup options
Download files from backup areas
Backup user data

Gonna amend the Academic Liaison Librarian, ASK, Technician, and Training to reflect these changes as they are currently a copy of this role.

**Comment by themarkness** [comment]
Set role to not allow editing of course details:

This should be duplicated to other editing roles aside from Learning Technologist
![screen shot 2013-09-26 at 16 56 29](https://f.cloud.github.com/assets/1681436/1219025/59d17ca6-26c4-11e3-9d27-75ff38ac7618.png)

**Comment by themarkness** [comment]
Okay, aside from Manage Files @oscott @damienh

**Comment by themarkness** [comment]
Done
