### ISSUE TITLE
Text displays outside of block

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#103]
In About this module, if text exceeds a certain length it displays outside of the block.
Tested in Chrome and Safari Mac

![screen shot 2013-09-23 at 16 36 10](https://f.cloud.github.com/assets/1681436/1192749/f0afeca8-2466-11e3-9d4d-67f900fc07ab.png)

**Comment by Asampson** [comment]
This is a duplicate of https://github.com/ucfalmouth/issues/issues/84
