### ISSUE TITLE
Live Chat - Back to module button isn't working on live chat

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#105]
This is the same problem that has been reported with other activities. 
http://learningspace.falmouth.ac.uk/mod/chat/view.php?id=6561

**Comment by ghost** [comment]
This has now been resolved. 

The issue was actually to do with the button **not working for going back to modules set to "show all on one page"**. The button now works if going back to a module page set to "show all on one page." 

To confirm, reported issue has been resolved.
