### ISSUE TITLE
Some links in the resources drop down dont work

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#107]
Looks like a few don't work and a couple go to email addresses, which I believe may not be good practice. Can someone please double check and fix

**Comment by damienh** [comment]
looks like one i cant see working is Dsylexia and thats because the url has 2 in it. I cant connect to the SAND? if its called that so I cant amend it. The email addresses are there as I coudnt find a space on the Learning Space or the intranet.

**Comment by ghost** [comment]
So what is the URL to Dyslexia Skills? Also, Software Training?

**Comment by damienh** [comment]
I will confirm it with Tom.

Many Thanks,

Damien Hogan
Learning Technologist

Falmouth University
Tremough Campus, Penryn, Cornwall TR10 9EZ

01326 255799
damien.hogan@falmouth.ac.ukmailto:damien.hogan@falmouth.ac.uk
etsupport@falmouth.ac.uk

# 

# I welcome VSRE emails. Learn more at http://vsre.info/

Centre for Pedagogic Arts-based Research (Pedare)

[cid:image001.png@01CE5080.DE1BC180]

View our work at http://pedare.falmouth.ac.uk
Join our community at www.pedare.ning.comhttp://www.pedare.ning.com
Follow us at @FalmouthPedare

On 24 Sep 2013, at 14:58, Aaron Marr <notifications@github.com<mailto:notifications@github.com>>
 wrote:

Dyslexia

[Falmouth University] http://www.falmouth.ac.uk/      [Follow us]     [Facebook]  https://www.facebook.com/falmouthuni      [Twitter]  http://twitter.com/falmouthuni     [Youtube]  http://www.youtube.com/falmouthuniversity  [Pintrest]  http://pinterest.com/falmouthuni

  This email is confidential and intended solely for the use of the intended recipient only. If you have received this email in error, please inform us immediately and then delete it.

**Comment by damienh** [comment]
Right @aaronmarruk spoke to Tom and it is dyslexia.fxplus.ac.uk and though it redirects to learningspace broken page atmo he is going to change it so it redirects to fxplus site while their page is being built on Toms site.

**Comment by ghost** [comment]
So what I will have to do now is remove the dead links. @oscott @damienh 

This will have to be picked up in another thread as: "Populating the resources menu."
