### ISSUE TITLE
Via Tender: Page Description Amendment - learn.falmouth.ac.uk

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#11]
Assigned to [Suggestions #9](http://et.tenderapp.com/discussions/suggestions/9-page-description-amendment-learnfalmouthacuk). As reported in Tender:

<blockquote><p>Can the description field for Add a page in learn.falmouth.ac.uk be switched to optional. Many thanks, Amy</p></blockquote>

**Comment by oscott** [comment]
we are happy for this to go ahead. When this is implimented, please let @aaronmarruk know that the functionality is available.

[ @oscott @damienh @themarkness @Patrick-ET ]

**Comment by themarkness** [comment]
Require activity description has been disabled. See attached
![screen shot 2013-07-16 at 09 58 39](https://f.cloud.github.com/assets/1681436/803571/fc56a044-edf5-11e2-832b-af457816bada.png)
