### ISSUE TITLE
"Learning Space Orientation"

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#117]
"Learning Space Orientation" – is this the correct language?

Why not something more simple like "Introduction to Learning Space"

or 

"Using the Learning Space"

**Comment by themarkness** [comment]
I would agree with "Introduction..." as it follows the format of some of the modules. We need to signify somehoe that this is a module within LS and the format is familiar.

**Comment by ghost** [comment]
Yes, that is exactly what I was thinking. We have been doing a great job with the language so far. So I was just pointing out that this should be changed to something "in keeping" with the rest of the language etc.

**Comment by themarkness** [comment]
Needs CM as we have already communicated the module title to staff and students.

**Comment by Asampson** [comment]
@damienh @os Amy - Video will need to be changed to reflect this.
