### ISSUE TITLE
Settings block hidding etc

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#128]
we need a final plan on blocks. Staff and students can see all blocks still?

**Comment by oscott** [comment]
@damienh got any time to pick up on this later with me please?

**Comment by damienh** [comment]
@oscott I will add it to my list and try tackle it today as its NFD.

**Comment by damienh** [comment]
having spoke to @Asampson it has been noted that the preferred method of hiding this block results in the + / - buttons at the bottom of the page for adding sections disappears. Naturally this is the best way for staff to add sections on the fly and is important. I am proposing can the settings block be hidden via css? Whats your thoughts @aaronmarruk @oscott
