### ISSUE TITLE
inconsistency in the module nav formatting

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#129]
http://learningspace.falmouth.ac.uk/course/category.php?id=167
http://learningspace.falmouth.ac.uk/course/category.php?id=168

**Comment by oscott** [comment]
ok - when you have more than 10 courses in a category, moodle outputs as table rather than a list. Info here: https://moodle.org/mod/forum/discuss.php?d=211311 no fix there yet though.

**Comment by ghost** [comment]
MOODLE CORE: Lib.php Line 37
Defines how many courses/modules are visible in "summary view"

```
/**
 * Number of courses to display when summaries are included.
 * @var int
 * @deprecated since 2.4, use $CFG->courseswithsummarieslimit instead.
 */
define('COURSE_MAX_SUMMARIES_PER_PAGE', 10);
```

**Comment by ghost** [comment]
```
define('COURSE_MAX_SUMMARIES_PER_PAGE', 10);
```

has been changed to:

```
define('COURSE_MAX_SUMMARIES_PER_PAGE', 100);
```

**Comment by ghost** [comment]
Ok, the above change is deprecated. This can be solved by updating settings in Admin: site administration/appearance/courses/ -> courses with summary limit.
