### ISSUE TITLE
Via Tender: Word Censorship - Learn.falmouth.ac.uk

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#13]
Assigned to [Help #17](http://et.tenderapp.com/help/discussions/help/17-word-censorship-learnfalmouthacuk). As reported in Tender:

<blockquote><p>Hi,<br>
English have noticed that some of their authors are being
automatically censored in the new LS - "Moorc**k's"</p>
<p>I haven't been able to recreate this on my machine in the office
but saw it happening on Chrissy Dennis' account when she was logged
in. I've tried logging in as her and also haven't been able to
recreate. Amy</p></blockquote>

**Comment by oscott** [comment]
I passed this setting last week, I'm pretty sure its a sitewide setting, so lets stick it through CM.

**Comment by oscott** [comment]
We have decided to turn this off sitewide. It can be enabled per course at a later date if required. ( @Patrick-ET @themarkness )
