### ISSUE TITLE
Forum Default Settings

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#130]
Getting some requests for default file sizes to be made larger in forums. Also can we up the file attachment amounts. 

Suggesting 9 attachments
and a 300 MB limit. 

Needs approval.

**Comment by themarkness** [comment]
Max file size is set to 100Mb by default, this can be changed for each forum but should be assessed for each course/module through consultation. Why large file sizes? Can you link to Vimeo, Soundcloud etc. @oscott @damienh @Patrick-ET
