### ISSUE TITLE
My Modules doesn't append a section 1 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#132]
Required for Monday. My modules doesn't append a section 1

**Comment by oscott** [comment]
Hear hear, I second that. This means the orientation is not as we want either.

**Comment by oscott** [comment]
Is this just a requirement for the front page?

**Comment by ghost** [comment]
yeah, there are a few pages around the site. My modules being one of them. I believe the "module search" results would be another. This can be done via jQuery.

**Comment by ghost** [comment]
Resolved. Pending theme update.
