### ISSUE TITLE
Styling in Category view 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#139]
http://learningspace.falmouth.ac.uk/course/category.php?id=78

Isn't styling correctly, had a complaint from Graphics. 

![screen shot 2013-09-26 at 14 12 43](https://f.cloud.github.com/assets/1598231/1217688/7f40a348-26ad-11e3-9c74-3603f572b631.png)

**Comment by ghost** [comment]
This is due to extra <p> tags being injected into the text. I suspect it is due to pasting from InDesign as she got advised it should be formatted according to a provided InDesign document. 

I believe @damienh was the contact for this. Any insights into what could be the problem?

**Comment by Asampson** [comment]
Was all formatted wrong inside the text fields with extra <p> tags etc. Have now fixed.
