### ISSUE TITLE
'pages' have a last updated message

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#141]
e.g. http://learningspace.falmouth.ac.uk/mod/page/view.php?id=7836

![52444868c6ba5d01c70000e0](https://f.cloud.github.com/assets/114344/1218433/84f5f39e-26ba-11e3-948b-68c2aa6c42cf.jpeg)

Is this appropriate? can it be changed through admin?

**Comment by ghost** [comment]
Blimey! I will get on it right away

**Comment by ghost** [comment]
Resolved. Pending theme update.
