### ISSUE TITLE
Module links should be above the section nav...

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#142]
... as modules with a large number of sections push the module links out of view

![screen shot 2013-09-26 at 16 16 13](https://f.cloud.github.com/assets/2537947/1218705/aa0eeed4-26be-11e3-97d8-fedce23f0040.png)

**Comment by Asampson** [comment]
Is this something that needs to be done manually @aaronmarruk? Or is it something we can do another way through db?

**Comment by ghost** [comment]
db

**Comment by damienh** [comment]
This will be done in #214
