### ISSUE TITLE
All courses must be set to "Show one section per page"

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#143]

**Comment by oscott** [comment]
How are we going to do this? db or manually?

**Comment by ghost** [comment]
db

**Comment by damienh** [comment]
will this cause issues for course shared/home pages?

**Comment by ghost** [comment]
probably yes. Didn't think of that... some manual config is in order then

**Comment by damienh** [comment]
Fair enough. When the change takes place we just need to make sure that there is maybe 2 of us to then quickly amend the course pages.

**Comment by ghost** [comment]
yeah sure. I can help if need be.

**Comment by damienh** [comment]
UPDATE mdl_course_format_options 
SET value = '1' 
WHERE name = 'coursedisplay' 
AND format = 'topicsdeluxe' 

Above will work to make any course thats using topics deluxe is set to show only one topic.

**Comment by damienh** [comment]
UPDATE mdl_course_format_options 
SET value = '0' 
WHERE name = 'coursedisplay' 
AND format = 'topics'

This will set any page set to topics to show all items on one page

**Comment by damienh** [comment]
Run this Query:

UPDATE mdl_course_format_options 
SET value = '1' 
WHERE name = 'coursedisplay' 
AND format = 'topicsdeluxe'

Then manually go to each "course home page" and set it to show all. This is the easiest way to change it for all modules. It shoudnt take 15min to amend the course pages and I am happy to do that.

**Comment by damienh** [comment]
Email for IT,

Hi Damian,

Below is the query that needs to be run on Moodle_24_Prod for the theme update on Tuesday morning by 10am subject to your change management.

UPDATE mdl_course_format_options 
SET value = '1' 
WHERE name = 'coursedisplay' 
AND format = 'topicsdeluxe'

**Comment by Asampson** [comment]
Email sent to IT
