### ISSUE TITLE
Orientation Module isn't appearing on everyones account

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#146]
The orientation module isn't being displayed on all accounts. Meaning when some students log in they go straight to the list of courses in schools etc. 

Example of a student who has this problem: Tom Austin 

Although when we log in as him it has it listed, but when he was logged in it wasn't on his modules page. If we find any more students who have this happen will add them to this issue.

**Comment by Asampson** [comment]
Also happening to Cameron Green.

**Comment by Asampson** [comment]
When they subscribe to another module it appears.

**Comment by themarkness** [comment]
Maybe the plugin is a bit flaky. If after they find their course and they subscribe it appears, it's probably okay no?

**Comment by Asampson** [comment]
It does appear once they subscribe, just wanted to flag it up really. In case we end up using it next year.

**Comment by Asampson** [comment]
Not sure anything else can be done about this for this year. One for next year.
