### ISSUE TITLE
Some fontawesome icons don't appear in FF

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#149]
![screen shot 2013-09-27 at 14 46 25 2](https://f.cloud.github.com/assets/114344/1226174/52ab5854-277b-11e3-99c3-bab8e54ed5ff.png)

**Comment by ghost** [comment]
I can't seem to replicate this issue. Can you provide some more information? 
Browser?
OS?
etc...

**Comment by ghost** [comment]
I couldn't replicate this issue.
