### ISSUE TITLE
Backups over 300mb arent uploading

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#15]
Looks like maximum upload size needs increasing temporarily to allow for large backup files to be added. I would say ideally 1GB for now and then can decrease once backups have been added. Its currently at 300mb. Iv assigned it to you Mark because your the only one I know who has access to the server.

**Comment by themarkness** [comment]
Approved by [@damienh, @themarkness and  @oscott]

PHP.ini has been edited so that post_max_size=1000M and upload_max_filesize=1000M
, this needs to be reverted to 300M and 500M respectively once @damienh has completed the work.

**Comment by damienh** [comment]
After the amendments to the php.ini file the error still continues. Moodle tracker states this as a fix https://moodle.org/mod/forum/discuss.php?d=228568 at several locations.

**Comment by damienh** [comment]
Unfortunately the code it recommends adding is already present.

**Comment by damienh** [comment]
Looks like large .mbz dont upload but a small folder does. Large zips sometimes do.

**Comment by themarkness** [comment]
This seems like a sub issue of #7
