### ISSUE TITLE
Attendance Module for LearningSpace - To be Installed. 

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#151]
Currently required module for courses to take attendance. This has been noted by 3D Design as critical for their stage 3's during their dissertations. I have installed and tested on learn-dev I just need the ok to go ahead and install it.

**Comment by themarkness** [comment]
This can be done as part of a wider project. Can this be created within Projects and communication go out to appropriate teams EDLS, QST. @damienh @oscott @Patrick-ET

**Comment by themarkness** [comment]
This has been installed.
