### ISSUE TITLE
Via Tender: old ASK_learningspace redirect

### ISSUE THREAD

**Issue by etsupport** [ucfalmouth/issues#152]
Assigned to [Email Query #2863](http://et.tenderapp.com/discussions/email-query/2863-old-ask_learningspace-redirect). Can do this, but we may need a cutoff as any course with that URL will be redirected to ASK

As reported in Tender:

<blockquote><p>Hello there gods of the learning space,</p>

<p>I have a query.</p>

<p>&nbsp;&nbsp;*   Might it be possible to arrange some sort of redirect for the old ASK learningspace course page url to go to ask.fxplus.ac.uk&lt;<a href="http://ask.fxplus.ac.uk&amp;gt">http://ask.fxplus.ac.uk&amp;gt</a>;?</p>

<p>We are working to get outdated links changed wherever we find them, but it seems likely that there will be some hidden out there. I think the old ask page was <a href="http://learningspace.falmouth.ac.uk/course/view.php?id=1611">http://learningspace.falmouth.ac.uk/course/view.php?id=1611</a></p>

<p>I would imagine the redirect would be possible in the htaccess (if you are on apache, I forget, I know you are on windows, but ISS/apache?). I would also potentially be interested to do the same for dyslexia and languages if this were possible</p>

<p>any ideas welcome</p>

<p>thanks!</p>

<p>Tom</p>

<p>[Falmouth University] &lt;<a href="http://www.falmouth.ac.uk/&amp;gt">http://www.falmouth.ac.uk/&amp;gt</a>;      [Follow us]     [Facebook]  &lt;<a href="https://www.facebook.com/falmouthuni&amp;gt">https://www.facebook.com/falmouthuni&amp;gt</a>;      [Twitter]  &lt;<a href="http://twitter.com/falmouthuni&amp;gt">http://twitter.com/falmouthuni&amp;gt</a>;     [Youtube]  &lt;<a href="http://www.youtube.com/falmouthuniversity&amp;gt">http://www.youtube.com/falmouthuniversity&amp;gt</a>;  [Pintrest]  &lt;<a href="http://pinterest.com/falmouthuni&amp;gt">http://pinterest.com/falmouthuni&amp;gt</a>;</p>

<p>&nbsp;&nbsp;This email is confidential and intended solely for the use of the intended recipient only. If you have received this email in error, please inform us immediately and then delete it.</p></blockquote>

**Comment by themarkness** [comment]
We will create a 404 page as otherwise people will not update their bookmarks. Links are in header of LS. @oscott @Patrick-ET @damienh

**Comment by damienh** [comment]
This has been resolved by Tom.
