### ISSUE TITLE
profile.php Blocks are on left

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#155]
Is this right? :)

**Comment by ghost** [comment]
I don't know what you mean.

**Comment by oscott** [comment]
yeah sorry blocks appear on the left rather than right else where. I think blocks arent supposed to be there either

**Comment by ghost** [comment]
no, the blocks aren't supposed to be on the left.
Not really sure what to do about this. Any suggestions?

**Comment by damienh** [comment]
I will take a look on learn-dev using a db query.

**Comment by damienh** [comment]
Is this still needed?

**Comment by ghost** [comment]
fixed with a new .php template for profiles.
