### ISSUE TITLE
learningspace.falmouth.ac.uk/itstudent for software training doesnt work 

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#158]
Hey All,

The above is being linked from this page http://www.falmouth.ac.uk/new-students/software-training on the main site so we need to address this. Ideally we need to go through and check all the alias's and redirects and check if they need to be added to the windows server.

**Comment by themarkness** [comment]
Couldn't they just have a hyperlink that goes to the correct address? Better than a redirect.

**Comment by Asampson** [comment]
@damienh has assigned this to @themarkness

**Comment by themarkness** [comment]
The link on the falmouth website needs to be updated if needed. Will notify Suzanne Travis.
