### ISSUE TITLE
Synchronise Course Enrolment with Category

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#16]
To enable course tutors to have access to all courses within a category rather than having to manually enrol

![screen shot 2013-07-16 at 10 21 34](https://f.cloud.github.com/assets/1681436/803689/38b48602-edf9-11e2-92ff-76e37c2ff566.png)

**Comment by oscott** [comment]
having meetings on Tuesday that will affect this - will wait til next CM.

**Comment by damienh** [comment]
Coupled with the image of the setting below and changing the enrolment method to have category first. I will change this on learn.falmouth.ac.uk to replicate it.

**Comment by damienh** [comment]
Solved.
