### ISSUE TITLE
Weird login error bug

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#160]
Content is pushed to the top of the sceen. Is difficult to read. Not sure why this occurs.

![screen shot 2013-10-01 at 12 05 21](https://f.cloud.github.com/assets/2537947/1244617/6f9adfa0-2a89-11e3-9a79-f8a3ae5a5e6e.png)

**Comment by damienh** [comment]
@aaronmarruk to style this block.

**Comment by ghost** [comment]
It's not perfect, but will do for now.

![screen shot 2014-01-07 at 15 09 59](https://f.cloud.github.com/assets/2537947/1860067/d4152a00-77ad-11e3-97bb-19901da8b684.png)
