### ISSUE TITLE
Hide format page settings for staff

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#164]
Within the edit settings staff are currently able to change the formatting options for the page, meaning that some staff are changing settings which is resulting in problems with Aaron's theme.

Can we hide: 

Formatting options for Topics deluxe format: Hidden sections
Formatting options for Topics deluxe format: Course layout 

This will mean the page settings wont change.

**Comment by ghost** [comment]
Good plan. Can I also be involved in this conversation please?

**Comment by Asampson** [comment]
Yes @aaronmarruk is there anything else you would like hidden in the edit page sections? 

http://learningspace.falmouth.ac.uk/course/edit.php?id=2

**Comment by Asampson** [comment]
@damienh @oscott Amy first part CA.

**Comment by Asampson** [comment]
Proposing that the whole of edit settings is turned off for the academic, Technician, Ask and academic liaison role.

Can't see anything in here which staff would need access to. Causing more problems having this available to staff as they are changing formatting etc.  

Currently unable to remove formatting options from this section.

**Comment by Asampson** [comment]
@aaronmarruk approved.

**Comment by Asampson** [comment]
@oscott @themarkness Approved.

**Comment by oscott** [comment]
@damienh could do with meeting Tom Scott and explaining module naming convention within LS.

Note: 1% and breadcrumb.

**Comment by Asampson** [comment]
Update Course settings - tested this to set to not allow. This then meant that staff were unable to use the ad sections feature at the bottom of each course page. 

Can't see a way to do what we want within course settings. Will this now be a matter of hiding with CSS? @oscott?

**Comment by Asampson** [comment]
Are these settings being hidden in the next update @aaronmarruk @oscott ?

**Comment by Asampson** [comment]
At this morning's UX meeting this came up as an action so assigning to @aaronmarruk

**Comment by damienh** [comment]
#128 References this.

**Comment by ghost** [comment]
UPDATE Jan 2014: If this is to be resolved I urgently need to know:

**What items in "Settings Block" do staff need access to?**

**Comment by ghost** [comment]
@damienh @Asampson @themarkness Please let me know re the above comment

**Comment by Asampson** [comment]
Features that are currently in Settings that are used as far as I'm aware are:

Question Bank
Switch Role to Student
Editing On
Users > Subscribed Users
Users > Enrolment Methods
Users > Groups

**Comment by Asampson** [comment]
Also when in forum settings staff should be able to amend the permissions which is also in this area. - http://etsupport.freshdesk.com/support/solutions/articles/178401-using-a-forum-for-course-module-notices

**Comment by oscott** [comment]
This is part of #128 and will be fixed in the 2.1 update

**Comment by oscott** [comment]
Apologies - we have decided to close #128 and keep this one open.

**Comment by ghost** [comment]
I have now implemented the block. Closing this as the reported issue has now been resolved.

**Comment by oscott** [comment]
Team are now divided on solution - items missed during approval, reopening issue.

**Comment by oscott** [comment]
We have decided to break this down into a few items:

<table>
  <tr>
    <th>ID</th><th>Issue</th><th>Sollution</th>
  </tr>
  <tr>
    <td>1</td><td>What - We need to control what is seen in the block</td><td>Needs controlling through permissions as separate issue</td>
  </tr>
    <tr>
    <td>2</td><td>Who - We need to control who sees the block</td><td>Needs controlling through permissions as separate issue</td>
  </tr>
    <tr>
    <td>3</td><td>Flow - Could UX be improved in a simpler way providing a 1st step to solution</td><td>toggling appearance of block - this should default to hidden</td>
  </tr>
    <tr>
    <td>4</td><td>Position - We need to control where the block appears</td><td>Using something similar to the "left region/column" and a default in the db, we could position a region as a tooltip/dropdown in the header or somewhere more appropriate</td>
  </tr>
</table>

Sub-Issue 1 + 2 should be dealt with at a later date and separately. 3 + 4 can be actioned now hopefully?

**Comment by ghost** [comment]
This issue, "Hide format page settings for staff" has been resolved – I have hidden the format page settings for staff.
