### ISSUE TITLE
Whos Online Block

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#166]
MA Professional Writing wanting to know if they can have whos online especially as they are purely online.

**Comment by Asampson** [comment]
@damienh this is only useful if profile pictures are used. At the moment I don't think we are using these within the system

**Comment by ghost** [comment]
@Asampson @damienh 

In a conversation recently with OS we talked about the possibility of user profile images. We could display lecturers profile images for each module description in the module list view. This would hopefully break up the largely text-based module list view and help students associate modules to the particular lecturer

The above is standard Moodle functionality (with a little bit of custom code to pull in the image, which I believe would be do-able).

So I guess the question is, do we allow profile images? We could then use profile images elsewhere around LS, for example, like this: (profile image next to my name)

![screen shot 2013-10-02 at 15 17 41](https://f.cloud.github.com/assets/2537947/1253927/7b93337c-2b6d-11e3-834e-1d32cd91f455.png)

**Comment by Asampson** [comment]
Where would these images come from? Could we some how get the ones from registry? Save creating an additional profile image somewhere.

**Comment by damienh** [comment]
The justification from Professional Writing was that its really the only method of students seeing who each other are ect. I no we are looking at turning the profile off but currently cant they add images that way?

**Comment by ghost** [comment]
I believe so. In general, I think profile images could be a nice way to break up the text-heaviness of the Learning Space. So they would be used more for the general "design" and aesthetic than anything else.

And yes, in the case of prof. writing they would be a good way to see who the other students are. This would also be true if used elsewhere.

So, the images would not necessarily be part of a "profile" but more of an embellishment of the text string of the persons name, e.g. "Aaron Marr [Profile Pic]"

So I'm in favour of using the Moodle Profile pics, as a mere image doesn't really mean we are using "Profiles" as such.

**Comment by damienh** [comment]
It would break up the forums which refers to this issue #165

**Comment by Asampson** [comment]
Could we get these images from registry?

**Comment by ghost** [comment]
I think we should use the moodle profile image as it is ready to go. See my previous comment as to why I believe this usage of "Moodle Profile Images" **does not** constitute to everybody having a profile in Moodle – something we are trying to avoid.

I think this requires change management

**Comment by damienh** [comment]
changes made in learn-dev I shall take a look later.

**Comment by Asampson** [comment]
@damienh To put in learn-dev for @aaronmarruk to approve. Then apply to Learning Space if Aaron's happy with next theme push.

**Comment by damienh** [comment]
@aaronmarruk I have enabled on learn-dev and can be found on this page http://learn-dev.falmouth.ac.uk/course/view.php?id=2

**Comment by ghost** [comment]
This is CM Approved and I have done the styling.
