### ISSUE TITLE
Assignment Marking View Needs Styling

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#167]
http://learningspace.falmouth.ac.uk/mod/assign/view.php?id=3754&action=grading

Can currently scroll both ways when marking assignments using the assignment plug in. This view should be tidier.

**Comment by damienh** [comment]
Duplicate Issue can also be found here #72

**Comment by ghost** [comment]
Fixed. 

You can now view in full screen mode. Failing that, the table is set to scroll, so you will get scroll bars. 

Use this button in breadcrumb to toggle full screen:
![screen shot 2013-11-01 at 15 15 40](https://f.cloud.github.com/assets/2537947/1454560/acab999a-430a-11e3-9958-52027900c9dc.png)

This is how it looks in full-screen mode:
![screen shot 2013-11-01 at 15 32 50](https://f.cloud.github.com/assets/2537947/1454577/e6f178d6-430a-11e3-862c-b2603e1ba267.png)
