### ISSUE TITLE
Module Section Inserted Images not resizing in IE 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#168]
http://learningspace.falmouth.ac.uk/course/view.php?id=504

Images used within the sections are not showing resized version when viewing on IE 10.

**Comment by ghost** [comment]
Aha! She is using height and width attributes and not height and width inline styles. She needs to use the proper inline style attributes, rather than plain (old skool) HTML attributes.

```
<img src="whatever" style="width: 100px; height: 100px;" />
```

rather than

```
<img src="whatever" height="100" width="100 /">
```

![screen shot 2013-10-04 at 12 28 32](https://f.cloud.github.com/assets/2537947/1268774/3409b5cc-2ce8-11e3-8c32-75b8b1ad9fb5.png)

**Comment by ghost** [comment]
What to do about Ann? Can somebody be in touch about this. Should we amend her code, or should she do it?

**Comment by ghost** [comment]
@etsupport anyone?

**Comment by Asampson** [comment]
@aaronmarruk I think we should amend it. She added it using the insert image settings within the WYSIWYG editor. Others are also doing them same, English had the same problem.

**Comment by ghost** [comment]
So it is Moodle added outdated/deprecated code that doesn't work. What a surprise. I don't know what to suggest on this one apart from turn off image uploads. Otherwise we'll be in there fixing things every five minutes because Moodle is spitting out invalid code.

**Comment by Asampson** [comment]
Don't think turning off image uploads is the right answer here.

**Comment by Asampson** [comment]
@etsupport any suggestions on this one?

**Comment by ghost** [comment]
**It appears there are 3 problems:**

**1.** The image sizing JS doesn't work in IE – I believe the YUI Library that does the actual "drag-resize" isn't functioning correctly in IE.

**2.** The "resizing" only actually adds width and height inline HTML attributes (See above). It doesn't actually resize the images. 
**2.b** This will undoubtedly cause issues on mobile browsers where bandwidth may be a premium and/or restricted as the "resized" image is still the same size on disk i.e. MB. 
**2.c** Adding inline HTML attributes actually causes images to be unresponsive, and so won't display correctly on Mobile, if the image is too wide for example.

**3.** Twitter bootstrap – the framework we are using as the base for the theme – actually overrides the inline attributes for IE, to overcome the issues re responsive images. This means that there are inconsistencies in the display of images as normal browsers display the resized image while IE displays them at the original size.

**Comment by damienh** [comment]
@Asampson purely as its one you added could you move this to the LS theme repo if possible. Damien

**Comment by Asampson** [comment]
Moved across as requested.
