### ISSUE TITLE
Attendance Activity

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#170]
The attendance activity has no help text associated with it. "There is currently no help associated with this resource or activity"

**Comment by damienh** [comment]
Hey Amy do you know of hand where helper text is defined or set?

**Comment by Asampson** [comment]
Yep its in the language file of the activity

**Comment by Asampson** [comment]
@damienh is this the right module - http://docs.moodle.org/24/en/Attendance_module ?

This is taken from the block description, maybe we can use this? 

"The Attendance module is designed for teachers to be able take attendance during class, and for students to be able to view their own attendance record.

A teacher can mark the attendance status of a student as "Present", "Absent", "Late", or "Excused". These status descriptions are configurable, and more can be added. 

The Attendance module can generate reports for either the entire class or for individual students. Students may also see their own attendance record if the activity is not hidden."

**Comment by Asampson** [comment]
@damienh do you think this would be appropriate?

**Comment by Asampson** [comment]
Needing some CM on this. @damienh any thoughts?

**Comment by damienh** [comment]
can be talked about at CM on the 25/10/13

**Comment by themarkness** [comment]
@Asampson @oscott Agreed.Change terminology to "you"

**Comment by Asampson** [comment]
The helper text isn't defined in this version and so we can't amend it. However in this post (https://moodle.org/mod/forum/discuss.php?d=235906) the creator of the module says it's should be included in the next update which came out in September. @damienh do you know what date the module we have was installed? Might be worth checking if this is the latest version?

**Comment by damienh** [comment]
Hi Amy,

Not sure on date but version is 2013070404. Version info for plugins can be found here http://learningspace.falmouth.ac.uk/admin/plugins.php its next to the type.

Many Thanks,

Damien Hogan
Learning Technologist

Falmouth University
Tremough Campus, Penryn, Cornwall TR10 9EZ

01326 255799
damien.hogan@falmouth.ac.ukmailto:damien.hogan@falmouth.ac.uk
etsupport@falmouth.ac.uk

# 

# I welcome VSRE emails. Learn more at http://vsre.info/

On 2 Jan 2014, at 10:57, Asampson <notifications@github.com<mailto:notifications@github.com>> wrote:

The helper text isn't defined in this version and so we can't amend it. However in this post (https://moodle.org/mod/forum/discuss.php?d=235906) the creator of the module says it's should be included in the next update which came out in September. @damienhhttps://github.com/damienh do you know what date the module we have was installed? Might be worth checking if this is the latest version?

—
Reply to this email directly or view it on GitHubhttps://github.com/ucfalmouth/issues/issues/170#issuecomment-31446484.

[Falmouth University] http://www.falmouth.ac.uk/      [Follow us]     [Facebook]  https://www.facebook.com/falmouthuni      [Twitter]  http://twitter.com/falmouthuni     [Youtube]  http://www.youtube.com/falmouthuniversity  [Pintrest]  http://pinterest.com/falmouthuni

This email is confidential and intended solely for the use of the intended recipient only. If you have received this email in error, please inform us immediately and then delete it.

**Comment by Asampson** [comment]
Meant to be included in this version but isn't and isn't something we can add.
