### ISSUE TITLE
Scheduler Student Numbers Max 9 or Unlimited change to 15?

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#171]
I just spoke with Graphics and they put forward an interesting number with regards to schedular. Currently for group bookings/events the max number is 9 or unlimited. They pointed out typically computer rooms are 15 so would it be possible to change it from 9 to 15. Anyone know about this?

**Comment by Asampson** [comment]
You can change this setting within the plug in settings. 

![screen shot 2013-10-07 at 15 58 19](https://f.cloud.github.com/assets/1598231/1281305/35cf102a-2f61-11e3-91d9-985d149dfa5c.png)

**Comment by damienh** [comment]
Cheers @Asampson I will put it on my list.
