### ISSUE TITLE
Default Line Spacing in Editor

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#172]
Hey Aaron,

Just spoke with Graphics and they mentioned that the line spacing between text looks quite large and they believe it is difficult for flowing text. Is there an option in the editor for line spacing? or is it something that is defined in the theme?

**Comment by ghost** [comment]
*\* SHORT ANSWER: As this has been reported by a couple of people now, I will have another look when we do a "theme review." **

Maybe the line-height is a little much (As pointed out by a couple of people). So maybe this will change but it will only be a minor 1px change if anything.

We will never allow academics to adjust the line-height in the editor as this would lead to horrific inconsistencies **

Ok. The line spacing is 1.5x which is standard for web readability these days. Most website these days use a standard typography system with line height of 1.5x – usually font size: 16px, line-height: 24px. We are actually using 14px on 21px (i.e. 1.5x line height) as the typography isn't responsive and needs to display on tablet and mobile.

Following are 2 examples of Websites designed by graphic designers for graphic designers. Note the line heights in the code editor. As you can see, the line-heights are at least 1.5. LS line-height is actually tighter than in the examples.

![screen shot 2013-10-03 at 14 24 41](https://f.cloud.github.com/assets/2537947/1261539/b443d506-2c2f-11e3-83ff-73f2687cc52b.png)

![screen shot 2013-10-03 at 14 25 48](https://f.cloud.github.com/assets/2537947/1261541/c05b5f26-2c2f-11e3-948a-8a02badab7b1.png)

**Comment by ghost** [comment]
@damienh Who asked this question, I would quite like to get in touch with them to talk about how we might improve the typography.

**Comment by damienh** [comment]
Mafalda Spencer mafalda@falmouth.ac.uk
