### ISSUE TITLE
Spell checker in WYSIWYG Editor

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#173]
The spell checker in the WYSIWYG editor underlines a spelling when its wrong but doesn't give any suggestions. People are clicking to repair the spelling but no suggestions.

**Comment by ghost** [comment]
This is the issue regarding the built in Moodle spell check. To enable browser spell check we would have to disable the moodle one.

**Comment by ghost** [comment]
@etsupport what shall we do? I recommend turn off Moodle Spell check

**Comment by ghost** [comment]
@etsupport anybody?

**Comment by Asampson** [comment]
If Moodle spell check isn't working then it's an improvement on what is there already.

**Comment by ghost** [comment]
We need to get some kind of vote so I'm assigning this to Change Management

**Comment by ghost** [comment]
assigned to this weeks milestone.

**Comment by Asampson** [comment]
@oscott @damienh Amy - Turn off Moodle Spell Check

**Comment by ghost** [comment]
Do it.

**Comment by oscott** [comment]
OK I had a look and once disabled we still have the problem of getting a tinymce right click instead of the browser one.

The fix to communicate out is:

Hold down the ctrl key when right clicking to get the usual right click menu.

Perhaps @Asampson this needs to go into knowledge base / training.
