### ISSUE TITLE
Amend Academic Role allow to duplicate content

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#175]
Currently the Academic rile doesnt allow staff to duplicate content inside a module. It was available in the old LS and was used to quickly generate forums for each weeks. Can people approve this for CM and I can make the change as I believe its just in the settings.

**Comment by Asampson** [comment]
Yep agreed

**Comment by damienh** [comment]
Update: I had a look through the settings yesterday and could not locate it. I have no asked susannah to look to see if she is able to see it on a different browser.

**Comment by Asampson** [comment]
Need some more information on this @damienh

**Comment by damienh** [comment]
Just did a test. I assigned my student account as an academic in the Educational Technology category on the LS and it does not show the duplicate button, however in as an overall admin it does show it. 

I will take another looking through the settings.

**Comment by damienh** [comment]
Ok this is not working on Learning Space as the following permissions have been changed:

Restore from files targeted as import needs to be allowed and so does Backup for import. Now these are enabled on Learn-dev but not on main LS. Does anyone know if these were turned off for a reason? Naturally I believe its to stop academics from backing up and restoring but just want to check @ucfalmouth

**Comment by damienh** [comment]
Currently myself and Mark have :+1:  this so we need just one more. can @ucfalmouth/learning-space-team please take time to go over it.

**Comment by damienh** [comment]
relies upon the following #128 #81 and can only happen once those have been completed.

**Comment by damienh** [comment]
@Asampson @themarkness @oscott approved it

**Comment by damienh** [comment]
Made changes and I can see it as a academic on my student account inside the example module. I have emailed Susannah Marriot to double check that she can see it.

**Comment by damienh** [comment]
Still waiting for clarification, however works for our tests so I am closing.
