### ISSUE TITLE
Turnitin : Submission type default to file upload

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#176]
At the moment within the Turnitin settings the default submission type is set to any type. Can this be changed to file upload?

**Comment by damienh** [comment]
@Asampson have you had a look in the plugin settings? It might be possible there.

**Comment by Asampson** [comment]
Not yet, just reporting it so there was a record. Will have a look into it.

**Comment by Asampson** [comment]
@damienh you can do it in the submission settings. Still needing CM before it can be actioned.

**Comment by Asampson** [comment]
@damienh @oscott Amy - Just having file uploads in here

**Comment by Asampson** [comment]
Has now been changed so default submission type is file.
