### ISSUE TITLE
Turnitin : Styling needs some work

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#177]
At the moment the styling within Turnitin needs some work. When logged on as an academic I'm unable to see the pencil that I need to use to amend dates. (Chrome). 

![screen shot 2013-10-03 at 14 17 34](https://f.cloud.github.com/assets/1598231/1261500/6ac37590-2c2e-11e3-8131-13135fb7eaae.png)

**Comment by ghost** [comment]
I greyed-out any empty rows so they are the same colour as the borders. This basically makes it look like those extra boxes aren't there.

**Note: Those boxes highlighted in the image above don't contain any HTML. They will only be greyed-out if they contain no HTML content.**

![screen shot 2013-10-04 at 11 49 48](https://f.cloud.github.com/assets/2537947/1268580/0216cff0-2ce3-11e3-8571-431dc6de2e67.png)
