### ISSUE TITLE
Turnitin : Date styling (Firefox)

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#178]
Within Turnitin as an admin editing dates the time options aren't displaying  correctly -  
![screen shot 2013-10-03 at 14 20 13](https://f.cloud.github.com/assets/1598231/1261511/bbe11e96-2c2e-11e3-81e6-9218579e5f55.png)

**Comment by ghost** [comment]
@Asampson I'll need a URL to this on the **DEV** site please.

**Comment by ghost** [comment]
OK, never mind about the URL I found it.

I have fixed this issues. Please also see the added "Tooltips" to make the form easier to understand.

See the "Minute" tooltip that appears when you hover over minute. Hovering over any of the other select boxes will display relevant tooltip.

![screen-shot-2013-10-04-at-11 25](https://f.cloud.github.com/assets/2537947/1268463/c0551002-2cdf-11e3-9bb5-b37a7ec3bd0b.jpg)

**Comment by ghost** [comment]
Pending theme update.
