### ISSUE TITLE
Turnitin : Parts settings

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#179]
Currently there is an option within Turnitin to use "parts". Just wondering if it's worth turning this off? Seems a bit confusing to students and I'm not sure we can use it yet.

**Comment by damienh** [comment]
Is this part as in e.g. an appendix?

**Comment by Asampson** [comment]
Nope as in multipart assignment

**Comment by Asampson** [comment]
@damienh @oscott Amy - Turn off parts

**Comment by Asampson** [comment]
Not currently able to disable this feature within Turnitin
