### ISSUE TITLE
Turnitin : Can't see assignment inbox (Chrome)

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#180]
Assignment inbox not viewable in Chrome. http://learningspace.falmouth.ac.uk/mod/turnitintool/view.php?id=9527&do=allsubmissions

![screen shot 2013-10-03 at 14 36 11](https://f.cloud.github.com/assets/1598231/1261591/e06c4234-2c30-11e3-8b9f-10c69991be4b.png)

**Comment by themarkness** [comment]
Needs plugin update to test fully. Servers snapshotted at 15.15 Agreed AM and AS

**Comment by ghost** [comment]
Ok, it is to do with Javascript loading. I am now loading the turn-it-in javascripts in the footer of my Theme. Not ideal but it works. This is hacky so I have added the hack tag to this issue. Please can somebody test the functionality (As I don't know what the functionality should be), and close this issue if all is ok.
![screen shot 2013-10-04 at 11 01 06](https://f.cloud.github.com/assets/2537947/1268324/57e2b590-2cdc-11e3-8b19-d0f54b2d3fbb.png)

**Comment by ghost** [comment]
@Asampson is this how the form should be?
http://learningspace.falmouth.ac.uk/mod/turnitintool/view.php?id=9527&do=allsubmissions

**Comment by ghost** [comment]
@Asampson is this ok now?

**Comment by Asampson** [comment]
Yep this is good. Just checked on firefox too and all good.
