### ISSUE TITLE
"Homepage" at same level as modules

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#182]
As I have mentioned, this is really confusing and needs to change.

http://learningspace.falmouth.ac.uk/course/category.php?id=167

![screen shot 2013-10-04 at 14 42 38](https://f.cloud.github.com/assets/2537947/1269554/0c95a808-2cfb-11e3-9b73-202dc7985785.png)

**Comment by ghost** [comment]
I don't know what the solution is but we should sort this out a.s.a.p @etsupport

**Comment by Asampson** [comment]
Will let @damienh explain.....

**Comment by ghost** [comment]
I think me and @oscott figured it out anyways... but we will have to speak about it soon.

**Comment by Asampson** [comment]
Yes please

**Comment by ghost** [comment]
@oscott should pick this up again...

**Comment by oscott** [comment]
@aaronmarruk will #204 temporarily fix - as in a first step in the right direction?

**Comment by damienh** [comment]
@aaronmarruk to work with @Asampson on getting a working local version.

**Comment by Asampson** [comment]
This is reliant upon the course categories being addressed. Eg removing stages from course areas. At the moment there isn't an appropriate place to move the course page. This has therefore been moved to Learning Space 2.2. @themarkness @damienh AS agreed.

**Comment by damienh** [comment]
This will be looked at through consultations to fix the navigation and category issues.
