### ISSUE TITLE
Link to ET Blog somewhere on the LS would be good 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#183]
Could really do with a link to the ET Blog somewhere on the Learning Space. At the moment you can only get to it through the move site, and this is only for posts tagged "the move" at the moment we're no longer using this tag, and so all other posts aren't really publicised, yet there is some really relevant things about the LS in there. Link would be fab and help us keep people in the loop with things ET

**Comment by ghost** [comment]
I will put a link in the Footer

**Comment by ghost** [comment]
Done.
