### ISSUE TITLE
Course Finder Blue Button -- Needs to be at top of page

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#188]
The course finder button has now gone to the bottom of the page. You can't obviously see it anymore and this is how we've communicated to staff/students to find their modules. 

![screen shot 2013-10-08 at 10 42 30](https://f.cloud.github.com/assets/1598231/1287765/24d3dfc4-2ffe-11e3-9583-cbb447615ecb.png)

**Comment by ghost** [comment]
This button is being removed from LS. There is a course finder link in the header
