### ISSUE TITLE
Courses button - takes students/staff to categories page 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#189]
The courses button at the moment takes students to the categories page. Not really a helpful view in my opinion and not something we really want the students to navigate to. Can this be changed?

![screen shot 2013-10-08 at 10 44 31](https://f.cloud.github.com/assets/1598231/1287785/71cadc2e-2ffe-11e3-8ec7-c407d7a7cf6b.png)
![screen shot 2013-10-08 at 10 44 40](https://f.cloud.github.com/assets/1598231/1287786/738dcf4e-2ffe-11e3-8cc4-c6b79d107a9e.png)

**Comment by Asampson** [comment]
Is this happening in the new theme @aaronmarruk ?

**Comment by ghost** [comment]
I'm closing this as "courses" link has been removed from header and so this is no longer a problem.
