### ISSUE TITLE
Migrate MBA to Production

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#19]
MBA needs to move to Production server. This has been agreed by all...

Hi Oliver

I have talked to Abbie we think it would good if we migrate the site to the production server on Wednesday the 24th as fits in well with us and the MBA students.

After talking to Altcom this morning, their requirements for the development of the new theme is simply FTP and MySQL access to the latest version of the site as they will be developing it locally; so migrating to the production server doesn't affect the planned theme upgrade.

What did arise from our meeting with Altcom, is that they would prefer me to upgrading the Moodle codebase to latest version prior them developing the new theme. 

I have previously successfully updated my local version to Moodle 2.3.7 so think going to Moodle 2.3.8 will be fine, but not sure about jumping to 2.4 or higher; ideally Altcom would like to go to 2.5.1.

As time is limited for all parties I was thinking that we could may be schedule an codebase update as part of the migration, limiting downtime to the students?
[I'm available on Tues/Wed next week to do the updates and migration it this works for you]

What version of Moodle are you using for the new learningspace?
Do think we should run the same version of Moodle to make support easier?

As I understand it from our conversation at Altcom this morning, they will be building a new the theme for the MBA Moodle site and I will continue doing site administration/support including updates.

All the best, Tim

On 17 Jul 2013, at 17:02, "Scott, Oliver" Oliver.Scott@falmouth.ac.uk wrote:

Hi Tim,

As discussed, we need to re-schedule the maintenance window for the MBA ASAP - preferably by the 26th. This is to move from the DEV server and increase resilience. We will need to start using the Dev server after that date. Can you please check the most appropriate time for a 2 hour maintenance window before then. I am copying in Maria and John (Altcom) so that they are aware. I have spoken with John and believe he is happy that this wont affect his work.

Let me know when's good,

All the best,

Oliver

**Comment by themarkness** [comment]
This is to take place on Weds 24th. [@oscott @Patrick-ET]
