### ISSUE TITLE
Styling in Quiz Activity

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#190]
Quiz activity styling needs to be looked at when using the question bank. The icons to preview questions are really small at the moment. See image. This is in chrome. 

![screen shot 2013-10-08 at 11 33 19](https://f.cloud.github.com/assets/1598231/1288106/3775d856-3005-11e3-8e45-a78ca38c4f8d.png)

Will set up a quiz in learn-dev and post the link here

**Comment by Asampson** [comment]
http://learn-dev.falmouth.ac.uk/question/edit.php?cmid=7073

**Comment by ghost** [comment]
fixed it.
![screen shot 2013-11-01 at 16 00 08](https://f.cloud.github.com/assets/2537947/1454820/ea05ab24-430e-11e3-81de-a126bcfe6cb7.png)
