### ISSUE TITLE
Return to module button not working in quiz

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#191]
Return to module button not currently working in the quiz activity. Similar to this issue - https://github.com/ucfalmouth/issues/issues/101

Example found here - http://learningspace.falmouth.ac.uk/mod/quiz/view.php?id=9992

In Chrome. 

![screen shot 2013-10-08 at 11 41 35](https://f.cloud.github.com/assets/1598231/1288156/4448440a-3006-11e3-8553-9bf2b42c3561.png)

**Comment by Asampson** [comment]
Here is a link for learn-dev - http://learn-dev.falmouth.ac.uk/mod/quiz/view.php?id=7073

**Comment by ghost** [comment]
bang, and the dirt is gone.
