### ISSUE TITLE
WYSIWYG editor for answering quiz questions - currently too large for window

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#192]
http://learningspace.falmouth.ac.uk/mod/quiz/attempt.php?attempt=4

Students viewing a quiz are currently seeing an oversized text editor. 
![screen shot 2013-10-08 at 11 43 42](https://f.cloud.github.com/assets/1598231/1288177/aac63750-3006-11e3-8744-630d68c6e390.png)
This is in Chrome.

**Comment by Asampson** [comment]
The comments section (which features below this one) is styling fine though - http://learningspace.falmouth.ac.uk/mod/quiz/comment.php?attempt=4&slot=2

![screen shot 2013-10-08 at 11 55 34](https://f.cloud.github.com/assets/1598231/1288258/42f6f9dc-3008-11e3-9c2b-354170522006.png)

**Comment by Asampson** [comment]
http://learn-dev.falmouth.ac.uk/mod/quiz/attempt.php?attempt=1

**Comment by Asampson** [comment]
This is it with different theme. 
![screen shot 2013-10-09 at 11 41 39](https://f.cloud.github.com/assets/1598231/1296720/79e35d38-30cf-11e3-8dfb-5a0659f36523.png)

**Comment by ghost** [comment]
In order to succeed, your desire for success should be greater than your fear of failure.
