### ISSUE TITLE
Quiz Activity - Marking Table Styling

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#195]
http://learn-dev.falmouth.ac.uk/mod/quiz/report.php?id=7073&mode=overview

![screen shot 2013-10-08 at 15 41 43](https://f.cloud.github.com/assets/1598231/1289998/ffd3212c-3029-11e3-80d0-e46918e01a2d.png)

Any chance this table could be made a bit more easier to read? Can be a bit hard to read when marking etc.

**Comment by ghost** [comment]
I have added the ability to full-screen any admin page.
Clicking this icon (at the end of the breadcrumb):
![screen shot 2013-11-01 at 15 15 40](https://f.cloud.github.com/assets/2537947/1454417/9462c0d6-4308-11e3-8af2-9f70c6d5cd4e.png)
toggles full screen mode. I believe this issue now is resolved, with the addition of this new functionality.
