### ISSUE TITLE
Unsubscribe page goes off screen

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#196]
Hey Aaron,

Susannah Marriot sent me this screenshot of unsubscribe page where trying to unsubscribe from a Forum. It looks like the box is running off the screen.
![picture device independent bitmap 1](https://f.cloud.github.com/assets/810107/1295943/7d8a855a-30bc-11e3-8151-5da20f9d5d4f.jpg)

Let me know if you want any more info.

**Comment by ghost** [comment]
I always need to know the exact browser (e.g. IE 8 – and if possible if it is in compatibility mode) and a URL, which I can just about make out from the screen grab.

For example, just saying "Firefox" isn't enough. I need the version please.

cheers.

**Comment by Asampson** [comment]
This looks like the enrollment view and not unsubscribe (which is in the settings block of the forum, see below). 
![unenrol - t - 1](https://f.cloud.github.com/assets/1598231/1296291/6a338c60-30c4-11e3-9a1e-34192ed503c9.png)

Also looks like the whole browser window is running off the page and not just the LS.

**Comment by ghost** [comment]
@damienh any idea what browser that is

**Comment by damienh** [comment]
@aaronmarruk Just been looking into it as found alternative to it. The actual browser from screenshot looks to be latest version of Firefox for Windows XP. I asked for specifics but she was unable to give me any. Here is a link to the page http://learningspace.falmouth.ac.uk/enrol/users.php?id=582

**Comment by damienh** [comment]
It goes off the screen for me as well but I can scroll right but she is unable to.

**Comment by ghost** [comment]
I can't seem to find an example of this on learn-dev. Could you point me to an example there @damienh

**Comment by damienh** [comment]
@aaronmarruk to take a further look via this url http://localhost:8888/learningspace/enrol/users.php?id=272

**Comment by damienh** [comment]
.enrolpanel {
display: none;
position: absolute;
background-color: #666;
padding: 0 5px;
z-index: 1000;
left: 0px !important;
min-width: 200px;
margin: 0 auto;
padding: 0 216px;
width: 100%;
}
