### ISSUE TITLE
we need a gallery solution

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#197]
@aaronmarruk @Patrick-ET im sticking this in here instead of the agenda.

**Comment by Asampson** [comment]
Still needing something for this.....had another request this week.

**Comment by Asampson** [comment]
Still needing a solution for this. Was requested again in a consultation yesterday. @oscott any suggestions? 500px was mentioned, do you know of anything else?

**Comment by themarkness** [comment]
Patrick has detailed this here:

https://docs.google.com/document/d/124yDU9pRXlXTy9my2qySai-UjQdzb5yiWbtVoBb8bjc/edit

**Comment by damienh** [comment]
@oscott we need to pick this up when your back after ChrimBo

**Comment by oscott** [comment]
I'm back - what's on?

What were we using in the old moodle?

**Comment by Asampson** [comment]
@oscott Iframes to custom galleries on our server. Also the old LS had a gallery option inbuilt.

**Comment by ghost** [comment]
I think a nice way to do this is:
1. People upload images to Moodle using built-in moodle image uploader
2. If there is more than one image, the images get shrunk down into a smaller thumbnail, which opens in a 'lightbox'

There is a little more to it, in that people may want to show a list of images in full size. There are ways round this so we should discuss the options and find a solution.

**Comment by Asampson** [comment]
There was also a lightbox function on the old LS. Which I assume was a plugin so we could look to see if there is an alternative.

**Comment by Asampson** [comment]
This is a Moodle plug in - https://moodle.org/plugins/view.php?plugin=mod_lightboxgallery 

Do you think this might work?

**Comment by themarkness** [comment]
Tried lightbox on dev, pretty clunky moodle way of doing it. We shouldn't probably be offering image upload facilty if there are better ways of hosting files on the web. Google shared folder/dropbox might work as well as Flickr but I think no-one is keen on Flickr.

**Comment by damienh** [comment]
Yeah iv mentioned Flickr and Google and a few staff have been a bit wary of who would end up owning the images.

**Comment by oscott** [comment]
Let's go with Aaron s suggestion. Project?

**Comment by damienh** [comment]
This is not a github issue more of something that lives on a task list. After meeting @aaronmarruk was going to look at it.
