### ISSUE TITLE
Via Tender: Add URL Activity

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#2]
Assigned to [Question #18](http://et.tenderapp.com/discussions/question/18-add-url-activity). As reported in Tender:

<blockquote><p>Add URL option in Moodle asks for a description, can this pleased be turned off in the same way as with file uploads, many thanks, Amy</p></blockquote>

**Comment by oscott** [comment]
I have now set this, but dependent on the outcome of the day, it may need doing again. (it is site admin also, but I thought it was safe to do.)
