### ISSUE TITLE
Via Tender: Error on learn.falmouth

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#20]
Assigned to [Help #19](http://et.tenderapp.com/discussions/help/19-error-on-learnfalmouth). As reported in Tender:

<blockquote><p>The attached error appeared on learn.falmouth.ac.uk on 23rd June 11:30am</p></blockquote>

**Comment by themarkness** [comment]
This should have been resolved by Site Administration > Server > Session Handling switching off Use database for session information. Moodle will now use file storage for session information. This should improve speed and database access.

**Comment by etsupport** [comment]
Hi,

Thanks for emailing Educational Technology, a member of the team will respond to you shortly. In the meantime, you might find what you are looking for in our knowledge base http://et.tenderapp.com/help/kb.

Check out our microsite too, http://et.falmouth.ac.uk . Here you'll find information on all the current projects our team are working on and ways in which you can help us.

All the best,

Team ET
