### ISSUE TITLE
Current week highlighting

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#200]
Hi Aaron,

Just wondering if the highlighting of weeks is supposed to look like the attached image. It seems like it's highlighted week as a notice and it's made the date seem less important.

Just thoughts.

![screen shot 2013-10-09 at 13 30 04](https://f.cloud.github.com/assets/1681436/1297274/94623922-30de-11e3-9e62-06add41ebae7.png)

**Comment by ghost** [comment]
Cool, yeah I see what you mean. Will have a look in the next iteration of the design.

**Comment by damienh** [comment]
@aaronmarruk will take a look at this.

**Comment by ghost** [comment]
I have removed the suspect styles as pointed out by @themarkness. I have opted to display a asterisk icon next to the title of the highlighted week. 

I think this is very effective as the star has high contrast compared to the rest of the design – it is asterisk-shaped and off-grid. This should draw user attention to the highlighted week.

![screen shot 2014-01-08 at 16 31 56](https://f.cloud.github.com/assets/2537947/1870069/6aa485f4-7882-11e3-86d1-71a04dbbe406.png)
