### ISSUE TITLE
Propose Academics can unsubscribe themselves from forced forums. 

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#201]
I would like to propose that academics can unsubscribe themselves from mandatory forums. I found that though they teach and want all students to get emails they dont want to receive themselves. 

What you do think.

**Comment by Asampson** [comment]
Make it so @oscott @damienh

**Comment by damienh** [comment]
Looking into this now

**Comment by damienh** [comment]
I have not found the best way for this to be achieved yet. I shall continue to look into it.

**Comment by damienh** [comment]
This can not be achieved if the forum is set to be forced to subscribe.
