### ISSUE TITLE
Disable HTML editing in Tiny MCE?

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#206]
I think we should disable HTML editing in Tiny MCE.
Can somebody pick this up. Check the implications etc...
@etsupport

**Comment by damienh** [comment]
We will explore the option of permissions within functions in tinymce @aaronmarruk action to add a tooltip on html button pointing/advising of dangers.

**Comment by damienh** [comment]
@oscott will also look at tinymce permissions.

**Comment by ghost** [comment]
The tooltips won't work as Tiny MCE is it's own little application that runs in an iFrame and so I can't target the button and trigger the tooltip.

**Comment by damienh** [comment]
with #222 in mind we need to clarify what the html button is used for. can @ucfalmouth/learning-space-team everyone please comment on how you see the html button is used.

**Comment by Asampson** [comment]
Embeds of various kinds.

**Comment by Asampson** [comment]
Vimeo & You Tube

**Comment by damienh** [comment]
Discussed and as the new theme strips classes defined in the html it is no longer needed.
