### ISSUE TITLE
"Problems with this page?" link for all pages

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#207]
In the original design there was a "Problem with this page" link at the bottom of all pages, used to report bugs and broken content within Learning Space.

The idea is the link uses a script to get the current URL, browser and OS (behind the scenes), and provides a form for the user to submit a bug/report broken content etc. The form then sends the reported issue, along with browser/os details to et-support.

I'm sure there must be a plugin for this but I can't find one. May be fun to develop a small plugin that does this if I get 5 minutes.

**EDIT** this is slightly more complicated as it would require PHP coding

**Comment by damienh** [comment]
In CM we agreed that @themarkness will take a look.

**Comment by themarkness** [comment]
This would be covered by Intercom should we roll it out. Have unassigned until a decision is made regarding this

**Comment by damienh** [comment]
I agree.

**Comment by ghost** [comment]
We need a solution on this asap and I think my original suggestion would be fine. I'm closing and  moving this into the theme repo.

https://github.com/ucfalmouth/LearningspaceTheme/issues/28
