### ISSUE TITLE
Automatic Vimeo Embeds 

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#211]
Automatic Video Embeds is causing a media duplication error. What is happening is if a user embeds a standard Vimeo embed code, you actually get 2 embeds appearing on the page. This is because Moodle's automatic embed functionality is turning the link back to Vimeo into another video embed.

@etsupport anyone have any views on how to best solve this issue?

See the highlighted link back to vimeo... this is being rendered as another video by Moodle:

![screen shot 2013-10-15 at 10 25 51](https://f.cloud.github.com/assets/2537947/1332498/e8e8a642-357b-11e3-94a6-0ff2bf286efd.png)

![screen shot 2013-10-15 at 10 27 37](https://f.cloud.github.com/assets/2537947/1332506/14260c00-357c-11e3-8e8b-26a5545d2a17.png)

**Comment by themarkness** [comment]
Just use Moodle embeds for media. It works for images and videos, though it doesn't seem to support mp3 in chrome.

Inserting the link to the video/image makes moodle embed the item

**Comment by damienh** [comment]
Do we need to provide documentation for this?

**Comment by oscott** [comment]
Have we had any negative feedback on this? unless we are currently promoting the inconsistent (moodle style) auto embed that only works for certain file types, and will force an external link to be an embed whether intended or not, I recommend we should switch it off. This is an outdated approach.

**Comment by Asampson** [comment]
I'm up for getting rid of outdated approaches. But either way the correct method needs to be communicated.

**Comment by oscott** [comment]
approved - will switch off auto embed. Team need to be aware incase any support calls come through. Post and KB needs to be written about embedding video /MW

[ @Asampson @damienh @Patrick-ET ]

**Comment by oscott** [comment]
Done /MW

Site Admin > Plugins > Filters > Multimedia Plugins - Disabled
