### ISSUE TITLE
Section 0

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#212]
Feedback has suggested that section 0 should be visible. What do you think of this latest iteration. We could potentially role this out with the next theme update. Thoughts.

@oscott @Asampson @damienh @Patrick-ET 

![screen shot 2013-10-15 at 11 19 36](https://f.cloud.github.com/assets/2537947/1332806/7c916b48-3583-11e3-8842-cc3232d812d2.png)

**Comment by damienh** [comment]
@aaronmarruk I like the new iteration. I believe it can be potentially misused especially if it contains large files.

**Comment by ghost** [comment]
I'm closing this as I have received feedback from the team and rolled into theme.
