### ISSUE TITLE
Delete HTML Block from Course Pages

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#214]
Navigation block needs to be pushed to the top of the page via a db query.

**Comment by damienh** [comment]
I shall be looking at this today.

**Comment by damienh** [comment]
@oscott We need to tie this in with the theme up date.

**Comment by damienh** [comment]
Ok this query works on dev:

UPDATE `mdl_block_instances` 
SET defaultweight = '-1'
WHERE blockname = 'html'

**Comment by oscott** [comment]
This block needs to be removed for modules, but still available on LShome page. Databse query needs to be written.

**Comment by damienh** [comment]
Amending above comment to delete all HTML blocks from all pages and then manually add html block to front page.

**Comment by damienh** [comment]
Hi Damian,

Below is the query to be run on moodle_24_prod on for the theme update on Tuesday morning by 10am subject your change management.

DELETE FROM mdl_block_instances 
WHERE blockname = 'html'

**Comment by damienh** [comment]
This is now on hold. New Query to set default weight does not work as it is taking the current page weight from a hash which cant be edited.
