### ISSUE TITLE
Workshop Activity Request

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#216]
Would it be ok to have the workshop activity added into the new LS? I know Anna in Art was using this for the workshop sign ups and it was being used quite effectively. Would be a shame to send her to an external service when we can do it within the LS.

**Comment by damienh** [comment]
@oscott @Asampson @themarkness approved and requires comms plan.

**Comment by Asampson** [comment]
Activity is actually called "Booking" and not workshop as first thought. Can this be installed onto new LS? @damienh @themarkness

**Comment by Asampson** [comment]
Can this be installed onto new LS? @damienh @themarkness

**Comment by damienh** [comment]
we will go over this on DEV

**Comment by Asampson** [comment]
@damienh has this been fully installed now? Can I close?

**Comment by damienh** [comment]
I wasnt aware I was to install it on live. I just aided with you to get it into dev to test. I dont have permissions on live server.

**Comment by learningtechnology** [comment]
You should have permissions now. Should go on with theme update.

**Comment by Asampson** [comment]
Assigning this to @damienh

**Comment by themarkness** [comment]
Will add for next milestone. Won't update on 28th Jan as there are too many hand in dates, have notified service desk that this will be added with theme update on Tues 4th

**Comment by Asampson** [comment]
If we keep it until the next milestone.

**Comment by Asampson** [comment]
Will be going up after theme update on Tuesday. @themarkness @damienh

**Comment by damienh** [comment]
Booking has now been installed and is being tested by @Asampson and will need CM if the tests are ok.

**Comment by Asampson** [comment]
@damienh All ok.

**Comment by damienh** [comment]
good will need to go to CM on Friday to be approved.

**Comment by damienh** [comment]
Being installed in the plugin update milestone.

**Comment by damienh** [comment]
@Asampson @themarkness we need to revisit this and look at having it for the next Academic year.

**Comment by Asampson** [comment]
@damienh and @themarkness @oscott is this something which now falls to IT Services given their recent take over of the server?

**Comment by damienh** [comment]
Indeed plugin requests are. It would be good to know the process for this as not sure we have ironed it out with the team.

**Comment by damienh** [comment]
√√√√√√√√√√√√√√√√√√√√√√√√√ @Asampson

**Comment by Asampson** [comment]
Amy to look and see if it's still available, see if it's the best one.

**Comment by oscott** [comment]
closing this as its now being looked at through the ET time trello board (years later)
