### ISSUE TITLE
Scheduler - Sending reminders?

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#217]
It's been reported that in the old LS reminder notifications from the Scheduler module did not send. Need to set up and test.

**Comment by Asampson** [comment]
Sends out notifications on original booking, just waiting to see if it sends a subsequent reminder.

**Comment by Asampson** [comment]
Doesn't send out reminder notifications. Will need to look into this further.

**Comment by oscott** [comment]
Looking here, I see no reference to reminders: http://docs.moodle.org/24/en/Scheduler_Module_capabilities

Also from what I can read above, there has never been this functionality. Unless someone can point out otherwise, the issue could perhaps be that moodle is misleading people and that we need to change some naming or something?

Any ideas @Asampson ?

**Comment by Asampson** [comment]
@oscott This is currently an option within the activity when you create a slot. Can't see why they would put this option in if it doesn't work properly. 

![screen shot 2014-01-10 at 14 30 08](https://f.cloud.github.com/assets/1598231/1887795/cbe44ffc-7a03-11e3-9c23-cffe78f72089.png)

**Comment by Asampson** [comment]
Looks like there is a fix here - https://tracker.moodle.org/browse/CONTRIB-1289?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel 

If someone is able to show me how to access this file on my machine I'll happily test on dev first.

**Comment by damienh** [comment]
Me and @Asampson had a look for that line it does not exist, however there is a new version of the plugin https://moodle.org/plugins/pluginversion.php?id=3616. Needs to be tested on DEV

**Comment by oscott** [comment]
Test on dev and add to LS update milestone if it behaves appropriately. @Asampson @aaronmarruk  @themarkness

**Comment by Asampson** [comment]
Will be tested on DEV on Thursday. Applied to live on Tuesday if ok. AS @themarkness

**Comment by themarkness** [comment]
Successfully installed on DEV. Can you test functionality@Asampson?

**Comment by Asampson** [comment]
I've tested some functionality but won't be able to test if reminders work until on live as cron isn't running on dev site.

**Comment by Asampson** [comment]
Tested on live, reminders still not working. @damienh can we try the fix that was mentioned before on this version? https://tracker.moodle.org/browse/CONTRIB-1289?page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel

**Comment by Asampson** [comment]
Not sure what else to suggest for this! @oscott @themarkness @damienh any suggestions?!

**Comment by Asampson** [comment]
Waiting until 2.7 when there is a better one available.

**Comment by oscott** [comment]
This is now fixed in 2.7
