### ISSUE TITLE
My Courses for Staff on Multiple Courses/Cohorts

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#218]
Hey @aaronmarruk 

I have had some feedback from staff who teach on multiple courses and also staff on Professional Writing who will be dealing with 3 cohorts from January, that their my courses page has become unusable because of the vast amount of modules being listed and especially when it lists the same module but for different cohorts on Prof Writing. 

Just wanted to make you aware to see if there is anything we can do to make it easier.

**Comment by oscott** [comment]
I believe this is a naming convention issue. @damienh Did you discuss this with Tom Scott?

**Comment by damienh** [comment]
This could be looked at through conditional formatting based on role. Should be looked at after the theme push as it is not essential.

**Comment by damienh** [comment]
Closing this as navigation will sort this.
