### ISSUE TITLE
Show activity reports - Set to yes

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#219]
Can we have activity reports set to yes in site admin.

**Comment by damienh** [comment]
need to check permissions and also check that it is on.

**Comment by damienh** [comment]
@oscott @themarkness @Asampson

**Comment by themarkness** [comment]
In M2.4 Activity reports are held within the Navigation block which isn't enabled for our site. This has been moved to course settings for M2.5, so should be fixed by an upgrade.

https://tracker.moodle.org/browse/MDL-31983

**Comment by oscott** [comment]
@aaronmarruk and @themarkness Do we need to take into account the recent changes Aaron made to the settings block for staff (due in 2.1 update)

**Comment by Asampson** [comment]
This should be fixed in the next update.
