### ISSUE TITLE
Student using two emails 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#220]
Student able to use two emails with LS. Damien assigned see email.

**Comment by damienh** [comment]
Had a look in the moodle database and no sign of the gmail account thats causing issues. I have emailed service desk to see if they have reference of it anywhere.

**Comment by damienh** [comment]
emailed the student today.

**Comment by damienh** [comment]
Student has not emailed back will be looking to contact member of the photography team.

**Comment by damienh** [comment]
Account has been deleted. Will wait for login again for details to be pulled from AD.

**Comment by damienh** [comment]
Looks like emails are still trying to be sent out. It could be that there is a loop in the logs.

**Comment by damienh** [comment]
IT have informed me that the google email is present on their records but under contact address field and not institutional email. Worth looking at our LDAP to see if we are pulling in the wrong field.

**Comment by damienh** [comment]
I have looked through the database and cannot find where this is being stored. This needs to be looked at further maybe together as I am out of ideas @etsupport

**Comment by oscott** [comment]
perhaps we are getting the wrong field from AD? but then if its not appearing in LS DB... so perhaps its a one off? @damienh is it definitely coming from LS?

**Comment by damienh** [comment]
From what I can gather we are no longer receiving emails from this student.
