### ISSUE TITLE
Scheduler - Tutors unable to add slots if already have student role

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#221]
Staff who were using the LS before being assigned roles currently aren't able to add slots on Scheduler bookings because of this. Is there any way of removing the student role for staff who have the academic role?

**Comment by damienh** [comment]
I cant remember if this was resolved via talking to each other @Asampson.

**Comment by damienh** [comment]
@Asampson can we go over this when we look at the plugin later today.

**Comment by oscott** [comment]
@Asampson @damienh forgive me for being a little slow off the mark - Why do we have Academics with Student role?

**Comment by Asampson** [comment]
@oscott When staff first log in they have a little wonder round to get familiar.....but in the role of a student. They subscribe to a few modules, then realise that they can't edit anything,

They give us a ring we assign the rights. But if they first visited the page as a student then this role over writes the academic role when it comes to this activity. Meaning Staff with editing rights can't add slots. 

Would be good if staff entering the LS for the first time are made staff users and not students. That might be a while off so for the moment a fix for this issue would be great.

**Comment by damienh** [comment]
This should be fixed by the new way we will handle roles.
