### ISSUE TITLE
File Uploads time out off campus

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#226]
Had several reports of file upoloads not functioning off campus, users have tried various file types sizes and locations.

**Comment by themarkness** [comment]
Will investigate from home on 22/10

**Comment by damienh** [comment]
I have had several members of staff have issue with this as well.

**Comment by themarkness** [comment]
Have tested using the following process. 23Mb file failed with error below:

**Testing for File Upload Learning Space

Test 1 - Drag and Drop
500K PDF, Image
1MB PDF, Image
6MB Image
23MB PDF

Test 2 - File Uploader
500K PDF, Image
1MB PDF, Image
6MB Image
23MB PDF

![screen shot 2013-10-22 at 10 11 26](https://f.cloud.github.com/assets/1681436/1380282/ac20c12c-3b02-11e3-9c7c-fa5e4716ddf3.png)

Have checked server: jpeg, pdf and mp3 files were being scanned for viruses ,so I have exclded them. Hasn't seemed to have made a difference.

There doesn't seem to be an easy way in Windows as in Linux to to get access to php error logs, so can't look into it any further.

**Comment by Asampson** [comment]
Max_Execution time = 600 
Max_input_time=600 

Changed TRWLTSWEB1

**Comment by Asampson** [comment]
upload_max_filesize changed from 10GB to 64MB

**Comment by Asampson** [comment]
Max_Execution time = 600 
Max_input_time=600

Changed TRWLTSWEB2

**Comment by themarkness** [comment]
Tested the following.

Upload 10MB pdf to Learning Space from home     1:50
Upload 10MB pdf to Learning Archive from home   1:45
Upload 30MB pdf to Learning Space from home     Server connection timeout at 3:00
Upload 30MB pdf to Learning Archive from home   6:04

FTP 30MB pdf to photography share from home     6:00 95.6Kbs
FTP 30MB pdf to trwltsweb1 from home            7:00 90Kbs

13.81 Down and 0.85 UP

Upload 30MB PDF to Learning Space through VMWare VDI < 0.01

This indicates that there is no change in upload speed (save for an expected minor decrease due to Windows processing/memory overheads) and that it is a PHP/Apache configuration issue. Nothing in the config indicates a problem.

**Comment by themarkness** [comment]
Test to see if zend configuration changes efffect php.ini on web1
 will comment out zend changes and add to php.ini

**Comment by themarkness** [comment]
FastCGI on Windows issue

http://stackoverflow.com/questions/17824462/internal-server-error-500-after-90-seconds-of-php-script-runing

http://httpd.apache.org/mod_fcgid/mod/mod_fcgid.html#fcgidcmdoptions

http://docs.moodle.org/24/en/File_upload_size#Modifying_the_IIS_7.0.2F7.5_configuration_.28Windows_Server_2008.2C_Windows_Server_2008_R2.29

**Comment by damienh** [comment]
This will be fixed when we move to the new server.
