### ISSUE TITLE
QuickMail 2.4 Version Install

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#227]
I would like to install the latest version of QuickMail which is for 2.4. The current version we have installed is for 2.3 but worked at the very start with 2.4. We currently have an issue where it wont email staff but only students. It would be good to see if this new version fixes this issue.

**Comment by damienh** [comment]
https://moodle.org/plugins/view.php?plugin=block_quickmail this the version.

**Comment by themarkness** [comment]
@Asampson @oscott Test on dev and if successful do on production next Tuesday DINT

**Comment by damienh** [comment]
I will look at getting this onto dev today and test.

**Comment by damienh** [comment]
the new version still only lets emails be sent to students and not Academics.
