### ISSUE TITLE
Acting Missing From Course Finder

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#229]
Acting is missing from course finder, however is included in the courses document within Google Docs. Is there any reason why it might be missing?

**Comment by oscott** [comment]
Works fine for me, Its the 1st in the list...

![526527fdc6ba5db7aa00006e](https://f.cloud.github.com/assets/114344/1372479/4fad3476-3a52-11e3-86bf-434d9607479e.jpeg)

**Comment by damienh** [comment]
could just be needing to clear cache.

**Comment by Asampson** [comment]
Have cleared cache. It's currently not appearing under A in the course finder. (Should have specified that in the first  instance!)
![screen shot 2013-10-21 at 14 47 15](https://f.cloud.github.com/assets/1598231/1372819/82fa02ea-3a58-11e3-86e9-c9755cc7e512.png)

**Comment by oscott** [comment]
ah i see so it does appear, it just doesn't appear in search results? looks like the HTML metadata for advertising is in acting.

**Comment by oscott** [comment]
fixed
