### ISSUE TITLE
File Upload - change terminology to reflect timeout 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#232]
![screen shot 2013-10-23 at 15 31 43](https://f.cloud.github.com/assets/1598231/1390591/39fb1f0e-3bf0-11e3-990e-9ff85aeafa03.png)

Suggestion from member of staff that this area has an additional disclaimer that students uploading from home will face a 10minute time out.

**Comment by themarkness** [comment]
Timeout issues will be notified by twitter and we need to start conversation around big files.

**Comment by Asampson** [comment]
No need to change the terminology here as the issue is more around educating staff about file sizes.
