### ISSUE TITLE
Exeter accounts currently able to log into new LS

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#233]
LDAP is currently allowing students to log into Learning Space. Reported to IT. Dave will be sending over the correct "user look up contexts" to sit within student LDAP. 

This will allow falmouth students and guest accounts to log in. Do we want alumi still to access the Learning Space? Also will need CM to change "user look up contexts".

**Comment by Asampson** [comment]
This is what needs entering:

OU=Fal Students,OU=All Users,DC=student,DC=fal,DC=ac,DC=uk

OU=Guest Accounts,OU=All Users,DC=student,DC=fal,DC=ac,DC=uk

Just needs CM.

**Comment by oscott** [comment]
Happy to approve testing this on learn-dev - perhaps patrick or steph can try logging in both before and after.

This is a big change to make and we need to be sure that we wont be locking anyone out.

**Comment by themarkness** [comment]
Agreed. We must document the old settings and make helpdesk and nathan  aware. @Asampson @oscott

**Comment by Asampson** [comment]
Tested with one student log in before changing any settings on learn-dev. Could get into ELE with login but not learn-dev or learning space. @Patrick-ET do you have access to any Exeter log ins we could test? Will ask Dave in IT if he has any we can test with.

**Comment by Asampson** [comment]
Have emailed Dave in IT again asking for text Exeter LDAP accounts.

**Comment by Asampson** [comment]
@oscott or @themarkness needing some help with this. I have two sets of contexts to put in to Learning Space - Fal Students and guest accounts but at the moment I can only see one area to put one context. Can someone work through this with me please?

![screen shot 2013-11-26 at 11 09 07](https://f.cloud.github.com/assets/1598231/1621344/7407126a-568b-11e3-80b4-43e9059d59cb.png)

**Comment by Asampson** [comment]
Have tested on learn-dev and doesn't allow student LDAP to log in. The DN that I replaced was: U=All Users,DC=student,DC=fal,DC=ac,DC=uk

**Comment by Asampson** [comment]
This has been applied to Learn Dev, CM to put this on live site?

**Comment by damienh** [comment]
@Asampson @themarkness @aaronmarruk all agree that this can go ahead when we are back after Christmas. It has been tested by Amy on dev.

**Comment by Asampson** [comment]
Have replaced OU=All Users,DC=student,DC=fal,DC=ac,DC=uk with:

OU=Fal Students,OU=All Users,DC=student,DC=fal,DC=ac,DC=uk; OU=Guest Accounts,OU=All Users,DC=student,DC=fal,DC=ac,DC=uk

Now active on the live LS.
