### ISSUE TITLE
Return to Module not working in Wiki

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#234]
Don't know if this has been sorted in theme update...#101 #191 @aaronmarruk can you verify and close if it has.

**Comment by ghost** [comment]
Fixed it. I'm using a different method that loops through the breadcrumb, finding the first link to "...course/view...php" (i.e. the module page) and printing it into a "Back to module button."

This method should fix all the other issues regarding the "Back to module" button and deep nesting of content, such as in forums, as it is linking to the first instance of a module page within the breadcrumb.
