### ISSUE TITLE
Code displaying in module description

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#238]
Code is displaying in the module description - http://learn-dev.falmouth.ac.uk/course/search.php?search=example 

![screen shot 2013-10-25 at 10 51 01](https://f.cloud.github.com/assets/1598231/1406813/66e71146-3d5b-11e3-87a5-ff4ed62eabda.png)

Chrome.

**Comment by ghost** [comment]
Why am I assigned? This looks like a content issue.

**Comment by ghost** [comment]
Setting module description to display HTML resolves the issue.
