### ISSUE TITLE
Via Tender: Description on resources - learn.falmouth.ac.uk

### ISSUE THREAD

**Issue by etsupport** [ucfalmouth/issues#24]
Assigned to [Help #23](http://et.tenderapp.com/help/discussions/help/23-description-on-resources-learnfalmouthacuk). As reported in Tender:

<blockquote><p>At the moment when you enter and description text to accompany a resource this text features underneath the resource itself once published. Can this be changed so that descriptions sit above a resource. Otherwise descriptions look like they belong to another resource when listed. Amy</p></blockquote>

**Comment by themarkness** [comment]
Assigned @aaronmarruk as there doesn't seem to be a way in Moodle Admin to do this.

**Comment by ghost** [comment]
Sorted (ish), it will do for now. I will look at all the elements throughout the site for the next iteration of the design and fix this properly. At least the reported issue is fixed. Improvements on the styling can come later.

![screen shot 2013-10-07 at 14 01 40](https://f.cloud.github.com/assets/2537947/1280509/93801aba-2f53-11e3-8fb4-dca39c8a2a9e.png)
