### ISSUE TITLE
Via Tender: Preview on internet

### ISSUE THREAD

**Issue by etsupport** [ucfalmouth/issues#243]
Assigned to [Suggestions #29](http://et.tenderapp.com/discussions/suggestions/29-preview-on-internet). As reported in Tender:

<blockquote><p>Hi</p>

<p>Is it possible for you to make learning space make a preview of common file types, such as jpg, doc, pdf, pptx and several others, similar to what several email clients have integrated to make the browsing easier and faster.</p></blockquote>

**Comment by oscott** [comment]
No we have no plans to do this - rendering previews of powerpoint files prior to download may be achievable by gDoc viewer? but it's not currently on the horizon.
