### ISSUE TITLE
StudentSMS Block only showing half 

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#244]
The SMS block as found here http://learningspace.falmouth.ac.uk/blocks/moodletxt/send.php is not showing all thats required. 

This is on Chrome on Mac OS and aso IE 10 on Windows 8.
![txttools](https://f.cloud.github.com/assets/810107/1454601/34e3b09a-430b-11e3-9538-2778a6094dd6.png)

**Comment by ghost** [comment]
I'm just looking at this on DEV

**Comment by ghost** [comment]
An example here: http://learn-dev.falmouth.ac.uk/blocks/moodletxt/send.php?course=2&instance=3779

**Comment by damienh** [comment]
Yeah i looked on dev and noticed it look slightly different. I shall assign this over to you. Keep me posted.

**Comment by ghost** [comment]
Have you tried debugging what is going on. Are you sure this is a theming issue?

**Comment by ghost** [comment]
I dealing with this bit... Fixing this hasn't really affected anything else on page...
![screen shot 2013-11-01 at 15 49 05](https://f.cloud.github.com/assets/2537947/1454747/2808334e-430d-11e3-8871-b710dddb46d5.png)

**Comment by ghost** [comment]
Just looks like another poorly designed moodle plugin... yay! 
Don't worry, I'll have a look at it

**Comment by ghost** [comment]
Ok, I fixed this issue.
It's ugly but usable.
