### ISSUE TITLE
View all sections option missing off mobile theme

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#245]
View all sections is currently missing from the mobile menu. This was in Chrome on iPhone. 
![photo](https://f.cloud.github.com/assets/1598231/1464869/902827e6-4555-11e3-80a9-43df9bc91f6d.PNG)

**Comment by ghost** [comment]
Fixed. Resolved, pending theme update.

![screen shot 2014-01-08 at 10 56 47](https://f.cloud.github.com/assets/2537947/1867632/af216e4c-7853-11e3-97c0-18e972bde213.png)
