### ISSUE TITLE
Via Tender: Downloading of Student Submissions

### ISSUE THREAD

**Issue by etsupport** [ucfalmouth/issues#247]
Assigned to [Email Query #7846](http://et.tenderapp.com/discussions/email-query/7846-downloading-of-student-submissions). When all assignment submissions are downloaded from Moodle, you cannot unzip the resulting file. You can still download individual files.

As reported in Tender:

<blockquote><p>Hi,</p>

<p>Have just downloaded all of the recent students submissions in CMT120 as a .zip file but I repeatedly get an error message when trying to expand them. Have downloaded 3 times and well as try and expand the archive in different locations. Have you encountered such errors before? Any help on how to resolve this would be much appreciated as I would rather not download each submission individually.</p>

<p>See attached for the error message that I get when trying to expand the .zip file.</p>

<p>Best,</p>

<p>Antti
<br>--
<br>Dr Antti Sakari Saario
<br>Head of Music</p>

<p>Falmouth University
<br>Academy of Music and Theatre Arts
<br>Penryn Campus , Cornwall TR10 9EZ</p>

<p>+44-1326-255925 (Office)
<br>+44-779-8632121 (Mobile)
<br>antti.saario@falmouth.ac.uk&lt;<a href="/help/discussions/email-query/7846/r?go=YXBwbGV3ZWJkYXRhOi8vNkE1MjJERTYtQzM3My00RUQ0LUIyN0MtNDdDOEY4QkIxQjg0L0FudHRpLlNhYXJpb0BmYWxtb3V0aC5hYy51ayZndA==" title="Link outside Support: applewebdata://6A522DE6-C373-4ED4-B27C-47C8F8BB1B84/Antti.Saario@falmouth.ac.uk&amp;gt">applewebdata://6A522DE6-C373-4ED4-B27C-47C8F8BB1B84/Antti.Saario@falmouth.ac.uk&amp;gt</a>;</p>

<p><a href="/help/discussions/email-query/7846/r?go=aHR0cDovL3d3dy5mYWxtb3V0aC5hYy51ay8=" title="Link outside Support: http://www.falmouth.ac.uk/">www.falmouth.ac.uk</a></p>

<p>[cid:43FE0DDB-9270-4EBC-86A6-535F4A050708]</p>

<p>[Falmouth University] &lt;<a href="/help/discussions/email-query/7846/r?go=aHR0cDovL3d3dy5mYWxtb3V0aC5hYy51ay8mZ3Q=" title="Link outside Support: http://www.falmouth.ac.uk/&amp;gt">http://www.falmouth.ac.uk/&amp;gt</a>;      [Follow us]     [Facebook]  &lt;<a href="/help/discussions/email-query/7846/r?go=aHR0cHM6Ly93d3cuZmFjZWJvb2suY29tL2ZhbG1vdXRodW5pJmd0" title="Link outside Support: https://www.facebook.com/falmouthuni&amp;gt">https://www.facebook.com/falmouthuni&amp;gt</a>;      [Twitter]  &lt;<a href="/help/discussions/email-query/7846/r?go=aHR0cDovL3R3aXR0ZXIuY29tL2ZhbG1vdXRodW5pJmd0" title="Link outside Support: http://twitter.com/falmouthuni&amp;gt">http://twitter.com/falmouthuni&amp;gt</a>;     [Youtube]  &lt;<a href="/help/discussions/email-query/7846/r?go=aHR0cDovL3d3dy55b3V0dWJlLmNvbS9mYWxtb3V0aHVuaXZlcnNpdHkmZ3Q=" title="Link outside Support: http://www.youtube.com/falmouthuniversity&amp;gt">http://www.youtube.com/falmouthuniversity&amp;gt</a>;  [Pintrest]  &lt;<a href="/help/discussions/email-query/7846/r?go=aHR0cDovL3BpbnRlcmVzdC5jb20vZmFsbW91dGh1bmkmZ3Q=" title="Link outside Support: http://pinterest.com/falmouthuni&amp;gt">http://pinterest.com/falmouthuni&amp;gt</a>;</p>

<p>This email is confidential and intended solely for the use of the intended recipient only. If you have received this email in error, please inform us immediately and then delete it.</p></blockquote>

**Comment by damienh** [comment]
This is now being looked at by IT as a wider issue.

**Comment by themarkness** [comment]
Found  this: https://tracker.moodle.org/browse/MDL-40245?page=com.atlassian.streams.streams-jira-plugin:activity-stream-issue-tab

Does assigment module have a timeout?

**Comment by oscott** [comment]
This needs to be tested on DEV to see if it works before we do anything drastic.

**Comment by oscott** [comment]
A quick note: Paul M, Mark W and myself found that the temp folder in moodle data root had mutiple copies of the file. We took one manually for Antii and removed the others. There havn't been any further requests for this. We all assumed that the multiple files were due to the process failing to complete.

**Comment by damienh** [comment]
Currently have a work around for this and will be fixed in the server move.
