### ISSUE TITLE
Course backup does not function

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#248]
Trying to back up the assignment activity in http://learningspace.falmouth.ac.uk/mod/assign/view.php?id=10830 results in browser downloading backup.php

Does this work for anyone else?

**Comment by damienh** [comment]
not sure havent heard of it. Not sure if this is assigned to me automatically? Or if i have forgotten I said I would look at it.

**Comment by oscott** [comment]
Hi @themarkness and @damienh Is this the same timeout issue we looked at with Paul M?

**Comment by damienh** [comment]
I have started to experience this again. I was able to backup a course 2 weeks ago but now cannot do a simple 1 topic backup.

**Comment by damienh** [comment]
This will be fixed by moving to the new server.
