### ISSUE TITLE
Forum Posts on Profile

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#250]
Hi Aaron,

on Learning Archive it doesnt show forum posts on the profile field like attached. It shows it on staff space so looks like it happens. 

![screen shot 2013-11-12 at 09 13 18 2](https://f.cloud.github.com/assets/810107/1520433/38212864-4b7b-11e3-8c67-fbf41ba43194.png)

**Comment by damienh** [comment]
Wanted to note that this is used by 2 courses for students to show their forum posts as part of module marking.

**Comment by damienh** [comment]
@aaronmarruk forgot to mention you.

**Comment by damienh** [comment]
http://learningspace.falmouth.ac.uk/mod/forum/user.php?id=7 works so the functionality is there but looks to be hidden from menu.

**Comment by themarkness** [comment]
Is this resolved now?
