### ISSUE TITLE
Moodle Navigation has appeared on Learning Space

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#251]
Any idea why? We now have 2 lots of navigation on every course and it looks pretty messy. Does it relate to #250?

![picture 5](https://f.cloud.github.com/assets/1681436/1525026/3843e8f0-4bcf-11e3-9718-0851e7e264ae.png)

**Comment by ghost** [comment]
Classic Damien. (Sorry @damienh )

**Comment by themarkness** [comment]
Should go through CM really, as that's the point of it.

**Comment by damienh** [comment]
Yeah relates to #250 its the "My Forum" posts thats needed for a submission this Friday for Photography. Naturally as its this Friday and was made aware yesterday it woudnt fit the Friday change management and coudnt test on learn-dev as it was being used yesterday afternoon.

**Comment by oscott** [comment]
So it looks like we have changed the whole LS navigation without agreement for the sake of 2 modules hand in? 

looks like we could just provide the links another way or only on the profile page.

Cant be too hard to hard code these links somewhere - with the user ID:

http://learningspace.falmouth.ac.uk/mod/forum/user.php?id=56
http://learningspace.falmouth.ac.uk/mod/forum/user.php?id=56&mode=discussions

We need to sort this ASAP - can I turn the block off now? IF it's for marking, then it wont be needed til next week? and is for even less users?

Seeing as it didn't go through Change Management, I think its ok to revert.

Any opinions?

**Comment by learningtechnology** [comment]
Got to do this stuff through CM in future. Will close as it has now been resolved
