### ISSUE TITLE
Jowan to be removed from Knowledge

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#254]
Hey @oscott Jowan has asked to be removed from the Knowledge. I looked for super user info but dont believe I have it. Can this be done by yourself?

**Comment by damienh** [comment]
@oscott any update on where the super admin details may live?

**Comment by damienh** [comment]
Can this be done using your account @oscott

**Comment by oscott** [comment]
@damienh  - I have removed his super permission and access to all groups.
