### ISSUE TITLE
permissions 

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#255]
Can I have permissions or block and mod folder on live site so when approved I can upload blocks or plugins or take them down.

**Comment by oscott** [comment]
Lets finely add a monthly security update on a tuesday morning to our annual plan and lump in plugins etc to only happen on those days. Damien will need additional perms. to do this.  ( **@damienh @themarkness** )

**Comment by ghost** [comment]
@oscott tie in theme update with this

**Comment by themarkness** [comment]
Damien now has editing permissions for these folders. Calendar event scheduled for first Tuesday of the month for team to update Moodle
