### ISSUE TITLE
Staffspace navigation doesn't work in course category view

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#256]
When viewing a course category eg. http://staffspace.falmouth.ac.uk/course/index.php?categoryid=2 the dropdown buttons in the navigation menu don't work. 

Known issue in Moodle with no resolution https://moodle.org/mod/forum/discuss.php?d=202508

Looks like it can't get info over HTTPS

![screen shot 2013-11-19 at 14 20 01](https://f.cloud.github.com/assets/1681436/1572877/d65697b6-5126-11e3-8978-f3c48ba3959c.png)

@aaronmarruk can you check if there is any way to resolve this?

**Comment by ghost** [comment]
Check this:
http://enable-cors.org/server_apache.html

**Comment by ghost** [comment]
Assigned back to @themarkness

**Comment by themarkness** [comment]
Added to .htaccess on staffspace-stage.falmouth.ac.uk. Doesn't resolve the issue. Only a problem on Navigation menu, not elsewhere
