### ISSUE TITLE
Copy learn-dev to ettest1.falmout.ac.uk for testing purposes

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#257]
Copy to live site so we can test. stuff
@Patrick-ET @damienh @oscott

**Comment by themarkness** [comment]
Copied to live, using dev database and datastore. Now requires Apache restart. Site is at learn.falmouth.ac.uk as Loab Balancer problems with ET test 1

**Comment by damienh** [comment]
To go to IT CAB. Let Paul Mornington know. [@oscott @themarkness ]

We currently have a url pointing to a test site on TRWLTSWEB1&2. The team are now required to test and debug a theme update as of next week (we'd like to start work from Weds). An apache restart is required on both web servers to enable this. This should have little risk for Learning Space etc. as the sites are load balanced. Can this be actioned through CAB.

**Comment by damienh** [comment]
As staff still have learn.falmouth.ac.uk bookmarked, we will need to differntiate our development site from our production site. Until we begin testing in 2014, the redirect will be re-added to learn.falmouth.ac.uk to point it back to learning space. We will request from CAB  that learn-stage be repointed to the Load Balancers to allow us to differentiate sites.  [ @Asampson @themarkness ]
