### ISSUE TITLE
Student Reps Added to Resource Menu

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#258]
Student Reps SLUGs meetings are starting and students need access to the area here http://learningspace.falmouth.ac.uk/course/view.php?id=714&section=1&section=1. Can this be added to the resources menu. They would have been in the original theme push but the area was not complete. 

I believe this will be made to both live and dev to keep them in sync.

**Comment by damienh** [comment]
Approved because this was promised for start of term as part of the move. Aaron to update on github theme and then on Web1.

Robocopy should then be run on Web2 [ @themarkness  @oscott ]

**Comment by ghost** [comment]
I updated the file. @themarkness to run robocopy.

**Comment by damienh** [comment]
@themarkness can you run robcopy?

**Comment by themarkness** [comment]
It runs at 3.30am every day. Manually triggered it, but should go to servicedesk in future
