### ISSUE TITLE
Module Tutors - Roles need to come from page role assignments and not category 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#259]
At the moment on the new theme the module tutors are being filtered at a course category level. This ideally needs to be at a module level as categories show most of the staff who wish to edit the whole area. 

![screen shot 2013-11-26 at 15 47 44](https://f.cloud.github.com/assets/1598231/1623437/ee7b126c-56b3-11e3-8880-a28fb0d44c81.png)

Looking at the Subscription settings of the page and inspecting the element shows the inherited roles next to the page assigned roles. 

Below is an inherited role:

![screen shot 2013-11-26 at 16 02 06](https://f.cloud.github.com/assets/1598231/1623463/32f3301e-56b4-11e3-9e49-7ccea330ce57.png)

This is an example of a role assigned at module level:

![screen shot 2013-11-26 at 16 02 18](https://f.cloud.github.com/assets/1598231/1623467/431181ee-56b4-11e3-95c4-d420ad405646.png)

The div changes depends on role. The academic role is the one that needs to be displayed on the module tutors so that means  "div.role.role_3" needs to be displayed in this area.

**Comment by oscott** [comment]
I think this is a great feature that would really help with relationships - there is obviously a permissions issue. probably more like a role issue. I think we need to closely consider roles and make sure the names being printed are right in the 1st place. 

I propose a new project regarding roles in LS. I'll chuck it in the next meeting agenda.

**Comment by oscott** [comment]
To ensure we don't get long lists of unexpected images on each category page - We could untick all from here: http://learn-dev.falmouth.ac.uk/admin/settings.php?section=coursecontact
Then over the next term, ensure the moodle roles for each user are correct and that there is a new policy to ensure this is kept up to date and eventually automated.

**Comment by oscott** [comment]
Can we check the status of the core hack #242 during this ETCM.

**Comment by Asampson** [comment]
Moving this to LS 2.2 as discussed in team meeting. This will be addressed as part of a roles/categories project. @damienh @themarkness AS

**Comment by damienh** [comment]
It is unclear what needs CM here. This is being done already, however we need to make sure each module has the appropriate people assigned.
