### ISSUE TITLE
Turnitin Integration Timezone not London GMT

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#260]
Tim informed me that the turnitin receipt he receives is not the UK timezone. Example below:

You have successfully submitted the paper, "Exploring automated and peer assessment: the tools underpinning Massive Open Online Courses" to the assignment "RESEARCH PROPOSAL - UPLOAD HERE - Part 1 (Moodle 1664532)" in the class "EDU170 – Discipline-based learning and teaching research (Moodle 657954)" on 27-Nov-2013 02:18AM. Your paper id is 27534071. Your full digital receipt can be downloaded from the download button in your class assignment list in Turnitin or from the print/download button in the document viewer.

**Comment by Asampson** [comment]
Sent a ticket through Turnitin to confirm which timezone we're in. Looks like this might only be the case on receipt notifications.

**Comment by oscott** [comment]
So I have read the forums and manuals -  the only way to do this is through a support ticket, which i'm assuming is what @Asampson did? if this is the case, then can we please chase it up for a response?

**Comment by Asampson** [comment]
Had a response and it's all sorted. Let @damienh know, he must have forgotten to close. Resolved :)
