### ISSUE TITLE
Archive pedare website

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#262]
Geoff Smith requested removal of site. This went through as ECM and needs documentation and archiving.

**Comment by oscott** [comment]
This was a temporary measure done via .htaccess redirect 301 to main falmouth site. We need to ask IT to redirect the DNS until further notice from Anne's office. What is the best way to archive this the wordpress site and content? [ approved by myself @Asampson @themarkness  ]

**Comment by themarkness** [comment]
Service Desk issue: F0342162
