### ISSUE TITLE
Stop Students Editing Email Digest

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#263]
So we have had issues with students not receiving emails or getting them up to 8 hours later than their fellow students. This is down to them editing the email digest setting in their profile. I dont believe they understand what the setting means. I am proposing we look at making it so they cannot edit this setting. 

Thoughts?

**Comment by Asampson** [comment]
@damienh I've known many students to change the digest settings and do know what it means. Maybe we should try educating them better on this setting rather than disabling it?

**Comment by damienh** [comment]
@Asampson do you feel there is a benefit for having it as a digest instead of email notifications as they come?

**Comment by Asampson** [comment]
Yes, sometimes students who are signed up to multiple modules who use forced subscription get a lot of messages. I think there should be the option to allow digest types. Just need to educate people on these settings if they are being used. What does anyone else think?

**Comment by oscott** [comment]
@damienh @Asampson - This needs to be discussed with Academic staff, if they expect emails to go straight off and don't know about the digest, then we need to manage expectations. What next?

**Comment by damienh** [comment]
This forms a KB archive. I will review the the tagging for said article. DH MW AS
