### ISSUE TITLE
Staff being able to log into Learning Space without having completed IT induction

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#268]
Presently staff are able to log into the Learning Space without having completed their IT induction. 

Any staff who have done this aren't able to receive email notifications to their institutional email address, they then bounce and come to the ET inbox. 

Have been in touch with IT who have said the following needs to be entered into LDAP authentication Moodle settings:  

OU=Fal Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk
OU=FXPlus Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk
OU=UEC Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk

Have asked IT for a test unauthorised account we can test on dev before applying to live. 

IT have confirmed that staff already who have accessed the system without authenticating will be locked out until they complete induction, upon induction they will have access to their old account.

**Comment by damienh** [comment]
This references #269 and can be done once changed. We are happy for this to be tested. Approved by @Asampson @themarkness @aaronmarruk

**Comment by Asampson** [comment]
Sent IT another email asking for a test account before I can trial in DEV.

**Comment by Asampson** [comment]
Now have a trial log in for an uninducted user, have also asked IT if the following DN's allow for guest access (external examiners). 

OU=Fal Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk
OU=FXPlus Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk
OU=UEC Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk

**Comment by Asampson** [comment]
Have now looked through with David in IT about who the DN changes would affect. 

There are 4 people this change would affect in the Learning Space, three of these are temps. 

Currently obtaining an alternative email address of a FT member of staff who we know uses the LS so we can let him know. 

Have also asked IT if the DN: OU=UEC Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk relates to Exeter staff as they don't need access to the Learning Space. 

Also asked about guest accounts, these apparently authenticate through student LDAP.

**Comment by Asampson** [comment]
OU=Fal Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk
OU=FXPlus Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk

Been in touch with IT who confirmed that the DN's we need for staff are: 

OU=Fal Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk
OU=FXPlus Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk

Will now test in dev. 

Original DN's
ou=allstaff,dc=staff,dc=fal,dc=ac,dc=uk;
ou=stagingoucuc,dc=staff,dc=fal,dc=ac,dc=uk;
ou=stagingoudca,dc=staff,dc=fal,dc=ac,dc=uk

**Comment by Asampson** [comment]
Tested with Patrick's Exeter login, which now doesn't work anymore with Learn Dev. Ready to be applied for 2.1.

**Comment by Asampson** [comment]
These DN's will be changed on Monday. By AS

OU=Fal Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk  
OU=FXPlus Staff,OU=All Staff,DC=staff,DC=fal,DC=ac,DC=uk
