### ISSUE TITLE
Enable global configuration for Aaron's "Section" Block

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#27]
http://docs.moodle.org/dev/Blocks#Enabling_Global_Configuration

**Comment by themarkness** [comment]
Done

**Comment by themarkness** [comment]
Not done actually

**Comment by damienh** [comment]
where are we with this now as its been open 2 months.

**Comment by themarkness** [comment]
Probably something that's a nice to have, not essential but useful.

**Comment by damienh** [comment]
This will now be done via DB query
