### ISSUE TITLE
Assignments - All subscribers listed as potential submitters

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#272]
At the moment within the LS a list of all individuals subscribed on a page are listed as potential submitters. Can this be changed so that only students are reflected in this list.

**Comment by oscott** [comment]
This needs a solution before coming back to ETCM.

**Comment by oscott** [comment]
Solution being suggested is to disable 'submit assignment' within the staff role. this needs to be tested on Learn-dev 1st but is approved for LS if a successful. - @Asampson @aaronmarruk

**Comment by Asampson** [comment]
This issue is related to staff inheriting the student role when browsing the Learning Space. Links to this issue also - #221 

Have checked roles and all the permissions in here are as they should be.

**Comment by oscott** [comment]
As solution to both #272 and #221, could we search for all with academic role and remove the student role from these users? using the following, you can query what roles each user has and remove as appropriate: http://learn-dev.falmouth.ac.uk/admin/user/user_bulk.php

**Comment by damienh** [comment]
This has to happen as and when issues are submitted and also we need to ensure when we assign academic roles we also remove student role for said module. Until we do LDAP staff roles we are unable to stop staff browsing around and subscribing to modules. @Damienh @themarkness @oscott. There was no clear action for change management on this so I have removed the label as there is nothing to approve. @damienh

**Comment by Asampson** [comment]
Automatic Enrolment would minimise this. Would then be able to look at roles.

**Comment by oscott** [comment]
moving this to: https://trello.com/c/K263gfG7/39-staff-managed-by-appropriate-data-source as this is from 1 year ago...
