### ISSUE TITLE
"Staff Training" link needs to go to etsupport website

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#273]
If we're keeping it, there is no longer any staff training area within Learning Space so we either need to remove it or change the link to go to et.falmouth.ac.uk
![screen shot 2014-01-16 at 09 17 36](https://f.cloud.github.com/assets/1681436/1928999/54fedaf2-7e8f-11e3-9305-013d585a03f8.png)

**Comment by Asampson** [comment]
ST have since added a few extra dates - they live here: http://learningspace.falmouth.ac.uk/mod/choice/view.php?id=16064

**Comment by Asampson** [comment]
Can this front button link to this area.

**Comment by oscott** [comment]
Approved - This needs to happen today. [ @Asampson @themarkness ] The button will soon go and people will do this via etsite

**Comment by Asampson** [comment]
@oscott this is still linking to the wrong place. We're currently publicising the training so would be great if this went to the right place.

**Comment by themarkness** [comment]
Done
