### ISSUE TITLE
Resize Option for profile description not available in IE

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#275]
The resize text box option available on other browsers isn't available on Internet Explorer. This has been reported by a student, just awaiting more detail about browser version. 

![screen shot 2014-01-17 at 09 17 00](https://f.cloud.github.com/assets/1598231/1940543/d4eda050-7f79-11e3-9460-900df2892227.png)

**Comment by Asampson** [comment]
Tested in browserstack, this option is missing for IE 10, 9 and 8. You can recreate this box in the user profile page under description. 

![screen shot 2014-01-24 at 11 56 44](https://f.cloud.github.com/assets/1598231/1994452/b440c876-84ee-11e3-9292-0e4d77c26202.png)

**Comment by damienh** [comment]
@Asampson can this be moved into Aarons theme repo please if possible.

**Comment by Asampson** [comment]
Have moved across.
