### ISSUE TITLE
Site wide support role for IT service desk - without manual subscriptions 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#277]
Could IT have a site wide role created where they are able to see any courses without having to subscribe. This new role isn't to have any editing rights and show the view of the student. There would be no emails with this role also.

**Comment by oscott** [comment]
Agreed as part of the new roles project: For now the solution is to use the non-editing academic role (almost identical to student role), check its perms. this should be renamed to non-editing staff. Once this is done, it can be assigned to the service-desk team. After that we need a plan to assign this as the default for all staff in place of the currently used student role. ( @Asampson @themarkness  )

**Comment by Asampson** [comment]
@damienh do you know how the current site wide roles with editing rights are able to avoid module subscription?

**Comment by damienh** [comment]
I believe its set in the permissions.

**Comment by Asampson** [comment]
@damienh do you have 30mins to look through this with me next week? Have been through settings and having some difficulty in not having manual subscriptions.

**Comment by damienh** [comment]
This should be moved to a personal task list.
