### ISSUE TITLE
Learning Space Login - Highlight Staff\ and Student\

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#278]
On the old LS we had it so that if a user entered "student\" or "staff\" it would prompt them with "Please don't use staff\ or student\". Could we have this implemented on the new LS? Speaking with IT they do have calls from staff and students unable to log in because they are using staff\ and student.

**Comment by oscott** [comment]
Approved - @aaronmarruk may have already implemented this in the new theme. ( @Asampson @themarkness )

**Comment by ghost** [comment]
Added a simple validation on the form.

![screen shot 2014-02-19 at 11 37 19](https://f.cloud.github.com/assets/2537947/2206038/49a3c3bc-995a-11e3-9e5d-f26395d89239.png)

![screen shot 2014-02-19 at 11 38 39](https://f.cloud.github.com/assets/2537947/2206041/70794980-995a-11e3-9c10-c19dcabea991.png)
