### ISSUE TITLE
Top menu bar has extra bit of black on it... needs removing

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#28]
![screen shot 2013-08-02 at 09 13 48](https://f.cloud.github.com/assets/1681436/899710/7db272be-fb4b-11e2-87d9-683cc41f1c42.png)

**Comment by ghost** [comment]
This issue has now been resolved. You will need to Pull theme aarontest from my GitHub @themarkness

**Comment by themarkness** [comment]
This has been reopened for CM

**Comment by themarkness** [comment]
This will be zipped and theme replaced. Remeber we now have to do this on both webservers using robocopy command or manually. @Patrick-ET @damienh
