### ISSUE TITLE
Design Centre Videos (IR) currently housed on dev

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#280]
This references #264. Currently the bespoke area we made for intuitive resources for Design centre is living in the learn-dev theme. This needs to be merged possibly into Aarons new theme under a section for Design Centre? This is needed by students as we speak, however students can access it just only inside the University. Mark Lea has been given a direct link to give to students. 

What are your thoughts?

@ucfalmouth

**Comment by oscott** [comment]
This requires no change management, just an update to the content. @damienh can you please do this. cheers.

**Comment by damienh** [comment]
@oscott That was done to my understanding. Can you confirm this?

**Comment by Asampson** [comment]
Done. @damienh
