### ISSUE TITLE
Remove AAT roles from Student Reps, Remove Student Reps Home and change Resources drop down to navigate to Category

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#281]
Subject to AAT handover of Student SSLGs to Departments in 2 weeks time.

SSLG and student rep information will be handled by departments, so their is no need for a 'Home' page. AAT no longer need Course Admin roles in Student rep category and the drop down should link to here:

http://learningspace.falmouth.ac.uk/course/category.php?id=178

**Comment by oscott** [comment]
Recommend that Rep content be managed through the awards pages in a new section by course admins. ( @themarkness @Asampson ) Needs comms 1st.
