### ISSUE TITLE
Popup is hidden behind page content when clicking on enrol Users

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#284]
Require this to manually enrol users.

http://learn-dev.falmouth.ac.uk/enrol/users.php?id=2&page=0&perpage=100&sort=lastname&dir=ASC

![screen shot 2014-02-10 at 09 51 30](https://f.cloud.github.com/assets/1681436/2124152/083dc0f8-9239-11e3-8b59-ed6e96a5a5e6.png)

**Comment by ghost** [comment]
Done it.
