### ISSUE TITLE
Clicking "Go" on course search navigates  to localhost

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#285]
Works first time, but not after that.
![screen shot 2014-02-10 at 10 04 23](https://f.cloud.github.com/assets/1681436/2124256/db4dd982-923a-11e3-9868-92130027bd5e.png)
![screen shot 2014-02-10 at 10 05 45](https://f.cloud.github.com/assets/1681436/2124264/edc26416-923a-11e3-97f0-ae61c950290c.png)

**Comment by ghost** [comment]
Resolved on my local dev theme. Pending theme update.
