### ISSUE TITLE
Enable User Profile Pictures for Theme Update

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#286]
User Profile pictures needs to be enabled for the new theme update. It lives under administration -> security -> site policies. Without this students will not be able to add a piccywickky.

**Comment by oscott** [comment]
Agreed @aaronmarruk @themarkness /MW

**Comment by damienh** [comment]
This is being hidden in current LS theme. New theme will make it available to staff and students.

**Comment by themarkness** [comment]
Done
