### ISSUE TITLE
Resources drop down

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#288]
needs a final going over, these are some notes to discuss:
- no longer needs creative futures as a parent item (software training is under the technical support anyway)
- "not listed, please make contact here" link needs changing.
- Perhaps resource centres shouldn't be a drop down.

**Comment by damienh** [comment]
I am currently looking at this now.

**Comment by damienh** [comment]
Theme is now on Learn-Dev for @aaronmarruk to bring over.
