### ISSUE TITLE
Maintenance Mode

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#290]
Maintenance mode within the new theme doesn't advertise that it's in maintenance mode until you log in. Can we have the theme so it's advertised it's in maintenance mode from the front page without logging in. This would avoid unnecessary calls to service desk when we are in maintenance mode.

**Comment by ghost** [comment]
I still would very much like to this tested on a vanilla theme please. 

Please report back functionality in a standard theme. Then, we will know if this is a theme issue or not.

@Asampson

**Comment by ghost** [comment]
This is standard Moodle functionality and not just the theme. If you are reopening this, please assign to somebody appropriate. Thanks.
