### ISSUE TITLE
styling the maintenance mode page

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#292]
Aaron has updated them maintenance mode page in theme. However, Moodle provides its own string in code from it's admin.php file. This makes appearance cluttered and isn't the right wording. 

The solution is to override the string through the language pack here: http://learningspace.falmouth.ac.uk/admin/tool/customlang/index.php

in there, we need to update admin.php from

```
The site is undergoing maintenance and is currently not available
```

to

```
Learning Space is undergoing some scheduled maintenance
```

 ( @aaronmarruk @themarkness  )

**Comment by oscott** [comment]
Was anything being done to the current page?

**Comment by damienh** [comment]
not sure what you mean? I am going to make these changes within the hour

**Comment by damienh** [comment]
All done.

**Comment by ghost** [comment]
I styled maintenance.php – this is how it looks on the **current** theme. I will need overwrite this file on live for the changes to take effect. @oscott 

We will also need to clear the theme cache on live. @damienh should this be added to your Running Order?

![screen shot 2014-02-24 at 13 28 35](https://f.cloud.github.com/assets/2537947/2245731/c268404c-9d57-11e3-86e8-a4a5b87e747e.png)

**Comment by ghost** [comment]
Sorry @damienh, I reopened this as action is still required. See my above message.

**Comment by ghost** [comment]
Issues all resolved. I have uploaded maintenance.php to live and @damienh has cleared cache.

**Comment by damienh** [comment]
all done, theme cache cleared.
