### ISSUE TITLE
Manual Software Training Link needs amending in resources menu

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#293]
The current link in for software training is going to the wrong page. Please can the software training link go this - http://learningspace.falmouth.ac.uk/course/view.php?id=686

**Comment by oscott** [comment]
This is relevant to #288 that doesn't appear to have happened yet, so shouldn't be an issue.

**Comment by ghost** [comment]
Done. I added the link to the new theme.

**Comment by damienh** [comment]
Added to menu on learn-dev.
