### ISSUE TITLE
Moodle Mobile

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#294]
Moodle Mobile plugin by PageOne has been tested on Learn-Dev and is ready to be switched when we do the plugin updates.

**Comment by damienh** [comment]
I am going to be retesting this on dev after getting our old credentials back from PageOne.

**Comment by damienh** [comment]
Approved @damienh @themarkness @oscott

**Comment by damienh** [comment]
New credentials send texts.

**Comment by damienh** [comment]
Please refer to settings on learn-dev for this module. I would paste here but passwords are sensitive.

**Comment by damienh** [comment]
this will be installed as part of the plugin update.

**Comment by themarkness** [comment]
Not sure we should go ahead with this, given that it hasn't been developed since M2.3. Should check  with developers.

**Comment by damienh** [comment]
Sent email to pageone support.

**Comment by damienh** [comment]
I got this reply:

Hi Damien ,

Sorry for such a late reply ,

It is our understanding that the MoodleMobile plug-in will work with Moodle 2.6.

Kind Regards

 http://www.pageone.co.uk/images/logo.png
Sean Lewis
Account Manager Tel: +44 (0) 20 8914 5342 | Fax:
+44 (0) 8450 518 700
 http://www.pageone.co.uk/sig-images/blue-bar.png
PageOne Communications Ltd | 12th Floor GW1, Great West House, Great West Road, Brentford, Middlesex TW8 9DF
www.PageOne.co.uk | join our LinkedIn page | follow us on twitter
This e-mail is confidential and may be privileged. It may be read, copied and used only by the intended recipient. If you have received it in error, please contact us immediately. Please consider the environment before printing this email

**Comment by damienh** [comment]
@ucfalmouth How do we want to go forward with this? 

currently the facts are:

1) its been tested and works on 2.4
2) developers say it works up until 2.6
3) There is no official release after 2.3

**Comment by damienh** [comment]
@themarkness your thoughts.

**Comment by Asampson** [comment]
This isn't an issue.
