### ISSUE TITLE
Notification Settings - Feedback Activity

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#295]
When notification settings are enabled for the feedback activity they send notifications to all site wide admin users. Need to look into notification settings and see if their are alternative settings will allow for notifications to be sent only to module staff and not site wide admins.

**Comment by Asampson** [comment]
There is a setting to turn this off in the role settings for course admin. Not sure it's something we should apply. Proposing to leave settings as they are and amend individuals roles/subscriptions should they be getting emails they don't want.

**Comment by damienh** [comment]
I believe that what you proposed is correct and should not be changed but we review where we apply roles.

**Comment by Asampson** [comment]
Still having an issue for this with site admins getting notifications. Amy - Need to look into fixes for this.

**Comment by Asampson** [comment]
Site admin role can't be changed. So any users with this role will always get notifications from any feedback module should the notifications be set to allow. Another reason to look at roles?

**Comment by damienh** [comment]
@Asampson can we move this into freshdesk?

**Comment by Asampson** [comment]
Moved across.
