### ISSUE TITLE
Update Student role profile to enable photo upload

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#300]
Doing this:
![screen shot 2014-02-26 at 10 32 33](https://f.cloud.github.com/assets/1681436/2268992/e4fd34fc-9ed1-11e3-92b4-42a4c9919acd.png)
Should enable this:
![screen shot 2014-02-26 at 10 29 37](https://f.cloud.github.com/assets/1681436/2268995/e819033c-9ed1-11e3-8ec0-542d6450a398.png)

**Comment by themarkness** [comment]
References #286. Approved @Asampson @oscott

**Comment by themarkness** [comment]
Didn't fix issue. Assuming it's them related:

https://github.com/ucfalmouth/LearningspaceTheme/issues/6

**Comment by ghost** [comment]
As per marks comment, **I don't think it's theme related.** See ucfalmouth/LearningspaceTheme#6

**Comment by themarkness** [comment]
Fixed as we hadnt altered the setting during the update,
