### ISSUE TITLE
Block Order Queries

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#301]
UPDATE `mdl_block_instances` 
SET defaultweight = '-999'
WHERE blockname = 'section'

UPDATE `mdl_block_instances` 
SET defaultweight = '-998'
WHERE blockname = 'course_menu'

UPDATE `mdl_block_instances` 
SET defaultweight = '999'
WHERE blockname = 'settings'

**Comment by ghost** [comment]
Approve @damienh @oscott
