### ISSUE TITLE
Change custom navigation menu

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#304]
The custom navigation blocks menu currently says about this Module. Which is a duplication of the new key information/module links area. Navigation is going to be something that takes a while to sort out so I'm proposing we manually remove these links or use a database call if this is possible? @damienh do you know if this would be possible?

**Comment by damienh** [comment]
It would need to be done manually. You woudnt be able to remove specific elements from a html block via the database unfortunately.

**Comment by damienh** [comment]
This has now been actioned out for an appropriate change management action and can be seen above.
