### ISSUE TITLE
Academic role unable to see module logs

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#306]
In the new Learning Space users with the academic role are unable to see logs for a page. Need to look into permissions as to why this is happening. Will test on Learn-dev.

**Comment by Asampson** [comment]
@aaronmarruk do you think there could be a way of hard coding this link in the current theme? At the moment this feature is enabled in the navigation block which we don't have.

**Comment by damienh** [comment]
http://learn-dev.falmouth.ac.uk/report/log/index.php?chooselog=1&id=COURSEID could work. If we can pass the course ID to it in a hard coded link that url should work.

**Comment by damienh** [comment]
http://learn-dev.falmouth.ac.uk/report/log/index.php?&id=COURSEID sorry.

**Comment by Asampson** [comment]
Spoken to @aaronmarruk and this is something which can be done in the theme. Have moved to other repo.
