### ISSUE TITLE
Unable to embed video from Screencast.com

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#310]
Rob Ingrum unable to post said inbeds into Forums. But is able to do so on Module pages

**Comment by Asampson** [comment]
Looks like this has happened before the screnncast.com - https://moodle.org/mod/forum/discuss.php?d=133862

**Comment by themarkness** [comment]
Could people use screencastify? https://chrome.google.com/webstore/detail/screencastify-screen-vide/mmeijimgabbpbgpdklnllpncmdofkcpn?hl=en

Chrome extension, saves to GDrive or Desktop in webm (open format for HTML5)

**Comment by damienh** [comment]
does it allow for embedding from gdrive?

**Comment by themarkness** [comment]
should do as it's webm
