### ISSUE TITLE
Scheduler - assigning roles as attendees

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#311]
Currently most roles within LS are being displayed against the attendee section of the scheduler activity. Proposing to amend roles on LS so that only ASK, Academic Liaison and Academics are listed as attendees. Have already tested on dev. @learningtechnology thoughts?

**Comment by themarkness** [comment]
I would propose that we do things like this, which are low impact and document them here:

https://docs.google.com/a/falmouth.ac.uk/forms/d/1HzWQTH3WcHpOVd6dzOfQdLis3UeWKN9siZrEd5Gti_o/viewform

**Comment by damienh** [comment]
Agree with @themarkness

**Comment by Asampson** [comment]
Have now put this through other system. Awaiting response on Friday 28th.

**Comment by Asampson** [comment]
@aaronmarruk @themarkness and AS approved. AS to change on live.

**Comment by Asampson** [comment]
Done
