### ISSUE TITLE
Tiny MCE theme 

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#313]
tiny MCE theme needs replacing on core upgrade

**Comment by damienh** [comment]
@aaronmarruk Hey we have a number of Professional Writing students being affected by this as they cannot interact with their course. Can this be a matter or urgency upon your return.

**Comment by oscott** [comment]
Fixed for now

@aaronmarruk Prof writing were reporting this seriously effecting the course. Therefore we have taken the lib/editor/tinymce folder from LS prior to last update and put it on the new version. Moodle have made no changes to that folder for the last year, so this was deemed a safe temporary measure. Can you please let us know if there are any other changes outside of that folder that need to be made. This will need documenting as core hack and to be added to the list of things to be aware of when updating LS (in tasklist template - redbooth)

**Comment by ghost** [comment]
Hi, that would fix it. I had a look through the folder(s) but didn't notice anything different.
I have had a look at the editor on live and all looks ok.
