### ISSUE TITLE
URL module duplicate for Talis

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#36]
duplicate the URL module and rename it Talis. This will be used to link to talis reading lists.

**Comment by damienh** [comment]
naturally this will be done on learn-dev first.

**Comment by themarkness** [comment]
This issue will be closed as we have decided to go down the route of using the existing URL module. Later we could do a find "reading list" in the DB and remove. We will also liaise with Librarians to assist with Talis work @Asampson @Patrick-ET
