### ISSUE TITLE
Labels not appearing for admin or create templates

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#39]
Hey Aaron,

Looks like your theme has removed labels and as a result they are no longer showing on the admin area or create templates e.g. for a forum or a assignment.

**Comment by ghost** [comment]
This has now been resolved.

**Comment by ghost** [comment]
Do the problems that Damien reported still persist?

**Comment by Asampson** [comment]
This links to #51

**Comment by themarkness** [comment]
Still has missing text with theme pulled on 27th August.

**Comment by themarkness** [comment]
Pulled theme 3rd September, seems to have fixed issue. Damien to check.

**Comment by damienh** [comment]
resolved with new theme update.
