### ISSUE TITLE
PDFs display odd

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#4]
On Wednesday - a decision was made to set all file downloads to default to "force download" - This was to ensure the browser or user computer made the decision on file display rather than moodle trying to render it the moodle way. This really makes a difference for mobile also.

**Comment by Asampson** [comment]
Have had comments from Journalism and PGCHE that PDF's aren't opening properly when set to force download.

**Comment by ghost** [comment]
What browser and Operating system is causing issues?

**Comment by damienh** [comment]
@Asampson Is going to look further into this and add it to Freshdesk to contact the people who reported it.

**Comment by Asampson** [comment]
Have emailed Bill, awaiting reply...

**Comment by Asampson** [comment]
Bill isn't sure of what particular browsers the students were using but he does think it's related to this. He managed to recreate the problem in the generic android browser. I'll have a look into doing some more tests on this.

**Comment by oscott** [comment]
I suggest this 6 month old but still relevant issue now takes form of a 1 hour et session on revising our download technique for LS - the solution will return to ETCM should we need to communicate anything. I'll stick an invite in the Cal.

**Comment by oscott** [comment]
I'm assuming this is now fixed
