### ISSUE TITLE
Via Tender: Insert Media Terminology

### ISSUE THREAD

**Issue by etsupport** [ucfalmouth/issues#42]
Assigned to [Suggestions #15](http://et.tenderapp.com/discussions/suggestions/15-insert-media-terminology). As reported in Tender:

<blockquote><p>Wondering if on the content editor the "Insert Moodle Media" could be renamed? At the moment I'm not sure this sums up this feature, plus it refers to Moodle when elsewhere we're trying to avoid Moodle as a term. Just a suggestion, might be a better term that could be used here as it also refers to any uploaded content users wish to add within a section.</p></blockquote>

**Comment by ghost** [comment]
Yeah, "Insert Media" or even "Add Media."

"Insert" is a little dry-sounding to me. "Add Media" is a little more straight forward.

What do you think? 

P.S. How can I notify the team? Like this... @etsupport ?

**Comment by Patrick-ET** [comment]
Add Media sounds better.

**Comment by damienh** [comment]
Has this been resolved?

**Comment by Asampson** [comment]
No

**Comment by Asampson** [comment]
Site Admin > Language Customisation > Select English (en) > Open Language Pack for editing.

On "Filter Strings Pages" > Only Strings containing "Insert Moodle Media" > Show Strings.

![screen shot 2013-09-19 at 13 50 22](https://f.cloud.github.com/assets/1598231/1172743/0bba4006-212a-11e3-90fd-c304bc086408.png)
