### ISSUE TITLE
Course Names

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#43]
Hi @etsupport @learningtechnology,

I noticed looking through learn.falmouth that some course names are very long. For example:

"BA (Hons) Music, BA (Hons) Creative Music Technology & BA (Hons) Popular Music." 

Is it necessary to have them listed as one course? I understand some courses need shared spaces but this causes a few issues:
1. The name is too long for inclusion in Navigation (The breadcrumb is really horrid)
2. Scanning course names is made more difficult (You have to read through to find the course you need)

One suggestion I can think of is removing "(Hons)" from (all) course names, resulting in:

"BA Music, BA Creative Music Technology & BA Popular Music." 

That is a little nicer, but has anyone got any ideas how we can separate these out? Are all modules really shared by all the courses? There must be a better way.

**Comment by ghost** [comment]
Ok, shortening it to:

"BA Music, Popular Music & Creative Music Technology" will possibly do the trick.

Thoughts?

**Comment by Patrick-ET** [comment]
Gets my vote.

**Comment by themarkness** [comment]
That reads to me as if its one degree. Id get rid of BA or add it to the others.

Mobile
