### ISSUE TITLE
Via Tender: Media Selector

### ISSUE THREAD

**Issue by etsupport** [ucfalmouth/issues#45]
Assigned to [Help #35](http://et.tenderapp.com/discussions/help/35-media-selector). As reported in Tender:

<blockquote><p>When using the new content editor you can select insert Moodle Media. From this screen select insert. You have an option here to select Wikimedia - which then presents an error message - "Incorrect sesskey submitted, form not accepted!"</p>

<p>Can this feature be removed/fixed please. Thank you!</p></blockquote>

**Comment by themarkness** [comment]
Amy commented in Tender that this is working again. Tender comments are not reported here. Is no good!

**Comment by themarkness** [comment]
Damien to test out
