### ISSUE TITLE
Via Tender: Parameter Option - Add URL

### ISSUE THREAD

**Issue by etsupport** [ucfalmouth/issues#46]
Assigned to [Help #37](http://et.tenderapp.com/discussions/help/37-parameter-option-add-url). As reported in Tender:

<blockquote><p>Hi,  
<br>&nbsp;&nbsp;&nbsp;On Add a Resource - URL you are taken to a screen where you can input URL and title. On this page is also a parameter option. Can this possibly be hidden as I believe it may be a feature not currently needed and could cause some confusion. Many thanks, Amy</p></blockquote>

**Comment by themarkness** [comment]
@oscott @damienh @Patrick-ET 

Not available in Site Admin. This can be hidden within CSS.

**Comment by damienh** [comment]
Where are we with this as it has been open a month now would be good to know if requires further attention or to be closed.

**Comment by themarkness** [comment]
It is hidden by default unless you click on "Advanced", I think we just wait and see if people enquire about it. What say you @Asampson ?

**Comment by ghost** [comment]
I've hidden it, as that is what was originally requested by @Asampson
