### ISSUE TITLE
Via Tender: Add a resource....URL

### ISSUE THREAD

**Issue by etsupport** [ucfalmouth/issues#47]
Assigned to [Suggestions #17](http://et.tenderapp.com/discussions/suggestions/17-add-a-resourceurl). As reported in Tender:

<blockquote><p>When adding a URL resource you can either input your own link or select the choose a file option. </p>

<p>choosing a file take you to another screen where you can use URL Downloader, Wikimedia and You Tube Videos. While I think having a link to You Tube is great, when trying to select videos from Wikimedia there is no way of previewing what you are able to select, nor is there much additional information as to what these are. </p>

<p>This feature could probably be quite useful but at the moment its hard to understand what it is you are searching. As this is a link to a URL option items inserted will be displayed as a link which you then click. Might be worth for the time being having this as just you tube and changing the terminology for the initial page so that "choose a file" is "link to youtube video". </p>

<p>Just a suggestion!</p></blockquote>

**Comment by Asampson** [comment]
Also had feedback from training that browse for URL is confusing. Could this be removed. Again a suggestion but as this has come from the first training session it's probably going to come up and an issue in the future.

**Comment by oscott** [comment]
perhaps the whole edit form needs simplifying?

**Comment by themarkness** [comment]
Can't see a way to do this in the URL Module administration, so it will have to be a language change or a CSS hide.

**Comment by themarkness** [comment]
The file picker has links to repositories, we could disable wikimedia and URL Downloader.

**Comment by themarkness** [comment]
Aaron to Hide "choose a file" in URL activity and @themarkness to remove URL Download activity. DH OS AS

**Comment by ghost** [comment]
@themarkness do you mean "Choose a link" rather than "Choose a file"?
![screen shot 2013-10-15 at 09 52 07](https://f.cloud.github.com/assets/2537947/1332286/25d943f4-3577-11e3-8795-eb58b2417b39.png)

**Comment by damienh** [comment]
Yes @aaronmarruk please remove a chose a link button

**Comment by ghost** [comment]
UPDATE Jan 2014: Fixed on my local install. This will be sorted once the new theme has been uploaded.
