### ISSUE TITLE
Via Tender: Moodletxt Renaming

### ISSUE THREAD

**Issue by etsupport** [ucfalmouth/issues#48]
Assigned to [Suggestions #19](http://et.tenderapp.com/discussions/suggestions/19-moodletxt-renaming). As reported in Tender:

<blockquote><p>Hello, 
<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Can we please rename Moodletxt to StudentSMS as per the old LS. This was under naming/terminology settings in 1.9. Thank you! Amy</p></blockquote>

**Comment by themarkness** [comment]
Agreed @Patrick-ET @damienh @oscott SC

**Comment by themarkness** [comment]
This has been done. See attached 
![screen shot 2013-09-04 at 09 21 06](https://f.cloud.github.com/assets/1681436/1078979/272e20aa-153b-11e3-97dc-d500ef5c0e6c.png)
