### ISSUE TITLE
Via Tender: Add a resource / Add an activity  options

### ISSUE THREAD

**Issue by etsupport** [ucfalmouth/issues#49]
Assigned to [Suggestions #21](http://et.tenderapp.com/discussions/suggestions/21-add-a-resource-add-an-activity-options). As reported in Tender:

<blockquote><p>Just checking with the settings that are currently included in the add a resource / add an activity options. Are these likely to be amended before launch, currently individuals can insert a database for example. Amy</p></blockquote>

**Comment by ghost** [comment]
Yes. These are Moodle admin settings. Tier 1 specification should give you an idea of what should be available by default.

We can allow tier 2 & 3 courses more options by default via a setting in Moodle admin.

Somebody from ET needs to look at this. I believe @damienh was looking at it.

Cheers.

**Comment by damienh** [comment]
It is a difficult one as I know we are attempting to get everyone onto tier one, however there are courses that already use databases in the old LearningSpace and as a result will need to use them in this version. I will add it for our meeting on Wednesday to discuss further.

**Comment by Asampson** [comment]
@damienh are we discussing this further at somepoint?

**Comment by ghost** [comment]
So by allowing "courses that already use XYZ in the old LearningSpace" – if this is happening across the board, this is tier 1 out the window? @damienh @etsupport

**Comment by damienh** [comment]
Its my understanding we cannot take anything away that they were using previously and this is where wiki's and databases come from. In terms of it effecting tier 1 that can be judged on a per activity basis. Is the option of being able to create a database to store information or a wiki really going to effect tier 1, I dont believe so. It does give us the opportunity to, once the academic year is in full swing, review how they are being used and provide guidance if appropriate.
