### ISSUE TITLE
enrolment not cascading

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#5]
enrolment of staff wasn't cascading from category down to multiple modules within. Amy has fixed this, but it need documenting

**Comment by damienh** [comment]
wasnt this fixed by Amy after she inducted English?

**Comment by oscott** [comment]
thats why i wrote: "Amy has fixed this, but it needs documenting" -

**Comment by oscott** [comment]
SIte admin > Plug-ins > Enrolments > Manage enrol plug-ins

Self enrol moved to top (settings changed defaults to add instance to new courses + self enrolments to yes - send course welcome message to no)
Manual enrolments
guest access
