### ISSUE TITLE
Scheduler activity missing option text 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#51]
In the same way as some text had gone missing from back-up/restore admin options, the same thing has happened with the Scheduler activity, initial setting up scheduler text has gone leaving only options left. Amy 
![screen shot 2013-08-22 at 11 19 12](https://f.cloud.github.com/assets/1598231/1007921/547417b2-0b14-11e3-9055-a3addeb10029.png)

**Comment by ghost** [comment]
This is a duplicate. Reopen the old post please @Asampson and paste this in so that all the information is available. 
Cheers.

**Comment by Asampson** [comment]
This is a duplicate of #39

**Comment by ghost** [comment]
Cheers Amy.

**Comment by Asampson** [comment]
This is happening for all resources and activity settings
