### ISSUE TITLE
Section Drag and Drop - Title Replace

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#52]
Pretty sure this is a bug. When dragging and dropping whole sections on a module page, when releasing the section the section takes the title of the section you have dragged on top of. Resources then feature in another section and the title of the section being dropped takes the name of the original section. Refreshing your browser resolves the problem.

**Comment by damienh** [comment]
I have this issue as well.

**Comment by themarkness** [comment]
Looks like it's a Moodle bug:

https://tracker.moodle.org/browse/MDL-34209

**Comment by ghost** [comment]
Could somebody look at this on a Module that uses a Vanilla Moodle module – i.e a module that uses only core themes and plugins? Does the issue occur when using core noodle plugins/themes etc?

Cheers.

**Comment by Asampson** [comment]
Having troubles recreating this, have used a plain theme and Aaron's theme and it's working ok at the minute, tried Firefox and Chrome. @damienh have you had any more instances of this happening?

**Comment by Asampson** [comment]
This issue has now just been reported happening again. Safari version 6.0.5

**Comment by Asampson** [comment]
@aaronmarruk is there way of keeping the drag and drop for documents/resources etc and having the old section up down arrows for moving individual sections?

**Comment by damienh** [comment]
This will be fixed in the process of updating security patches 2.4.7

**Comment by damienh** [comment]
RE the comment above from Amy it is one of the other. The manual one only loads when AJAX fails.

**Comment by oscott** [comment]
We need to assign a date to this.

**Comment by damienh** [comment]
This looks to be part of the security patch milestone. This needs a date and @themarkness has recommended that it could be done on the day of the theme update, subject to test on dev. I agree. @ucfalmouth whats everyones thoughts?

**Comment by damienh** [comment]
@themarkness is this something we can just do or does it effect the theme?

**Comment by damienh** [comment]
@themarkness is this something we can just do or does it effect the theme?

**Comment by damienh** [comment]
This will be done on Tuesday the 1st of April as part of the Security Update.

**Comment by damienh** [comment]
Security update took place and PW no longer have the issue.
