### ISSUE TITLE
News Forum Requests

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#55]
We've had requests from staff in the training sessions if the news forum can be added, you currently can't add a news forum in the forum options. The only way (I believe) that you can have a news forum is by adding the block again, which currently can't be added as we disabled it from the block menu. 

The news forum is a preferred option of contact as students aren't able to reply and they receive an email update when something is posted in this forum. This would mean a change in system settings.

**Comment by themarkness** [comment]
Agreed. We will make available, but advise should be given to courses on appropriate method of course communication. Also, this should be renamed as "Notices" @oscott @Patrick-ET SC @aaronmarruk

**Comment by themarkness** [comment]
Information can be found here:

https://moodle.org/mod/forum/discuss.php?d=31992

Looks like its a case of adding news forum site wide and then adding a news block and then removing it.

**Comment by themarkness** [comment]
![screen shot 2013-09-19 at 09 54 24](https://f.cloud.github.com/assets/1681436/1171537/3ae7583a-2109-11e3-8140-b9a5df108eb4.png)

**Comment by themarkness** [comment]
This can be achieved by
1)Creating a Standard Forum named "Notices"
2)Click on settings cog for Forum
3)Click on Permissions
4)Click on Override student role
5)Click on Prevent "Start New Discussions"

**Comment by damienh** [comment]
Ok so do we have an action on this now? or do we need to propose one for CM?

**Comment by themarkness** [comment]
We did approve this, but the only way to do it is how I've documented it above. We'll need to go through each course that requires it and add the "Notices" forum.

**Comment by damienh** [comment]
Hmm maybe we need an extra label stating we are going to use this to refer back to as otherwise issue list will continue to grow.

**Comment by themarkness** [comment]
Just need to document it in KB

**Comment by themarkness** [comment]
Have written how to in KB so will close. 

http://et.tenderapp.com/help/kb/staff-support/using-a-forum-for-coursemodule-notices
