### ISSUE TITLE
Training URL for Vicki

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#56]
Hi, 
  This week in the huddle I mentioned that we needed another short URL for Vicki to use in sessions where staff could be directed to the new learn training area. Currently this is set up as learningspace.falmouth.ac.uk/t1 in the current system. We need an equivalent for the new system. 

Was told to put it in here as an issue. Will also have to go to IT change management. 

Thank you!

**Comment by themarkness** [comment]
Agreed. Will be done on Monday @Patrick-ET @SC @oscott 

http://learningspace.falmouth.ac.uk/training

**Comment by themarkness** [comment]
Done
