### ISSUE TITLE
Section_block is out of date

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#57]
Receive this message when running security updates within moodle. Can this be fixed/removed for next week.

**Comment by ghost** [comment]
I believe this has been resolved. Our version of this block is called "Section_Fal" https://github.com/aaronmarruk/section-fal

I think you may need to delete the hacked block, and then re-add the core block from the official Moodle distribution... if that makes sense.

As a side note: we are actually using the core version in the current learning space, and not our custom version.
