### ISSUE TITLE
Turnitin

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#59]
This currently isn't working within the Learning Space. Does anyone know why? And how we can fix it?

**Comment by damienh** [comment]
Required PHP settings 
In order for the module to work correctly you must enable support for cURL in your 
php.ini file. 
To do this you need to locate the following line in their php.ini file: 
;extension=php_curl.dll 

OR 

;extension=php_curl.so
Remove the semi-colon at the start of the line to activate the php cURL extension. 
Once you remove the semi-colon the web server service needs to be restarted. 
More information on cURL and more detailed instructions for installing it can be found 
here: http://uk3.php.net/curl

Required Moodle setting

Within config.php, the default setting for dbpersist needs to be:
e.g. $CFG->dbpersist=false;

**Comment by themarkness** [comment]
Agreed. Config.php should be backed up and then the chnage made. Test this on dev @Patrick-ET @oscott SC

**Comment by themarkness** [comment]
curl is installed and dbpersist is set to 0

**Comment by Asampson** [comment]
Looks like someone is having the same issue as we are: https://www.jiscmail.ac.uk/cgi-bin/webadmin?A2=MOODLE-UK;9b28f507.1303

@damienh

**Comment by themarkness** [comment]
Check dis stuff too! http://www.sslshopper.com/apache-server-ssl-installation-instructions.html

**Comment by themarkness** [comment]
Moodle looks for certificate in Moodledata folder. Have downloaded curl certificate, renamed and placed in moodledata.
