### ISSUE TITLE
Save and display option

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#60]
If you select ‘Save and Display’ rather than ‘Save and return to course’ you get taken to a resource page which has the option to open that resource, if you then click the ‘back to module’ button it doesn’t take you back to your course page as expected, it takes you back the resource editing page. 

Can we possibly loose the option to select "save and display"?

**Comment by damienh** [comment]
Also I have found that the back to module button comes up with Invalid Operations error.

**Comment by damienh** [comment]
Will these remove it as an option for scheduler or assignment for example as well?

**Comment by themarkness** [comment]
This is a temporary fix. Amy to disable in module and pass to aaron if it needs to be hiddern @Asampson @damienh @oscott

**Comment by Asampson** [comment]
There is a way this can be hidden within the code of Moode - https://moodle.org/mod/forum/discuss.php?d=240104

@aaronmarruk can you have a look at doing this?

**Comment by Asampson** [comment]
There is a way this can be hidden within the code of Moode - https://moodle.org/mod/forum/discuss.php?d=240104

@aaronmarruk can you have a look at doing this?

**Comment by damienh** [comment]
This cannot be done via the CM Approved way. CM needs to be done for Amys proposed above.

**Comment by damienh** [comment]
Had a look at the above proposed by Amy and it looks like a alteration to php my code which we want to stay clear of. @aaronmarruk will take a look via the theme instead. Add a forum as an example. It will be at the bottom of the page.

**Comment by ghost** [comment]
UPDATE Jan 2014: I have sorted this issue via a change to my local dev theme. This will be finally resolved once the new theme is live.

NOTE: I also changed the button text to "Create forum" rather than the wordy "Save and return to course"
