### ISSUE TITLE
Server Files

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#61]
At the moment an option called "Server Files" - Do we think this needs to be changed in the admin settings so that academics can not have access to this option? 

"The server files repository enables teachers and managers to access files used within a course and elsewhere on the site which they have permission to access."

"When a file from the server files repository is re-used elsewhere on Moodle, the teacher has the option to make a copy (a new, unconnected version) or to create a shortcut or alias. See Working with files for more details."

Not sure if having this available to staff would create a bit of a file structure nightmare?

**Comment by themarkness** [comment]
Agreed @Patrick-ET SC @oscott 

This needs to be turned off in repositories

**Comment by themarkness** [comment]
Done
