### ISSUE TITLE
Student File upload (for Moodle assignment)

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#62]
When a student goes to upload a file for an assignment you can do this via drag and drop but also you can add a file through the file picker. From here you can view recent files (not sure if this is necessary?) as a student you also have the option to create files too. Not sure if there is a way of narrowing down the options available for student file uploading? 

![screen shot 2013-09-05 at 13 58 25](https://f.cloud.github.com/assets/1598231/1088094/e8cfb918-162a-11e3-9c86-c6fcee1c1cbe.png)
![screen shot 2013-09-05 at 13 58 16](https://f.cloud.github.com/assets/1598231/1088096/f18ee538-162a-11e3-9e36-93ead1d67ca3.png)

**Comment by themarkness** [comment]
This can be done in Manage Repositories
![screen shot 2013-09-05 at 14 13 08](https://f.cloud.github.com/assets/1681436/1088176/07c277d2-162d-11e3-9cc9-12d6372182c8.png)

**Comment by Asampson** [comment]
Thanks @themarkness - shall we go over this in CM tomorrow?

**Comment by themarkness** [comment]
Agreed SC @Patrick-ET @oscott #recentfiles

**Comment by themarkness** [comment]
Done
