### ISSUE TITLE
SSL Connection - Chat Module

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#64]
Getting the following screen shot when using chat within learn.falmouth.ac.uk

Suggestion that this could be linked to the problems with Turnitin (https://github.com/ucfalmouth/issues/issues/59). 

(I'm using Chrome)

![screen shot 2013-09-05 at 15 27 12](https://f.cloud.github.com/assets/1598231/1088685/6494f386-1637-11e3-8d98-8d7e4778c732.png)

**Comment by Asampson** [comment]
Getting the following in firefox for the same chat area. 
![screen shot 2013-09-05 at 15 33 21](https://f.cloud.github.com/assets/1598231/1088744/33fcd8e6-1638-11e3-8980-27a1a1f7a850.png)

(Accessible interface works on both)

**Comment by damienh** [comment]
changed the settings to AJAX chat and now works.
