### ISSUE TITLE
Choice Activity Formatting Issue Chrome 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#65]
The choice buttons are currently formatting strangely in Chrome when set to horizontal. 

Firefox: 
![screen shot 2013-09-05 at 16 05 27](https://f.cloud.github.com/assets/1598231/1089057/4a794d98-163d-11e3-88c2-0c4cdf30a6ab.png)
Chrome: 
![screen shot 2013-09-05 at 16 05 20](https://f.cloud.github.com/assets/1598231/1089058/50f4c468-163d-11e3-9096-658c5b18800d.png)

**Comment by ghost** [comment]
I need an example of this on learn-dev please (with URL) @Asampson

**Comment by Asampson** [comment]
@aaronmarruk http://learn-dev.falmouth.ac.uk/mod/choice/view.php?id=4796

**Comment by ghost** [comment]
This is now resolved.
![screen shot 2013-10-08 at 09 58 44](https://f.cloud.github.com/assets/2537947/1287524/23177caa-2ff8-11e3-8390-7cbd559f5646.png)
![screen shot 2013-10-08 at 09 58 56](https://f.cloud.github.com/assets/2537947/1287526/277523ec-2ff8-11e3-8153-c87fb5849e95.png)
![screen shot 2013-10-08 at 09 59 02](https://f.cloud.github.com/assets/2537947/1287528/2a5c3988-2ff8-11e3-82ad-5c157a13d099.png)
