### ISSUE TITLE
Activity/Resource Description Text

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#66]
Moodle is referenced in both the Scheduler and Turnitin descriptions within the activity/resource picker. 

As references to Moodle have been taken out from the Learning Space can this reference also be removed from this description.

**Comment by themarkness** [comment]
This needs further investigation. Does anyone know where/how this can be done?

**Comment by Asampson** [comment]
Would there be a description text/file in the Scheduler/Turnitin plug ins? Could try and find the description text within the plug in files and replace?

**Comment by Asampson** [comment]
Turnitin:

Site Admin > Language Customisation > Select English (en) > Open Language Pack for editing.

On "Filter Strings Pages" > Only Strings containing "Creates a Turnitin Moodle Direct" > Show Strings.

![screen shot 2013-09-19 at 14 01 31](https://f.cloud.github.com/assets/1598231/1172830/4f48fd7e-212c-11e3-922a-a6f65b97e8d6.png)

**Comment by Asampson** [comment]
Scheduler:

Site Admin > Language Customisation > Select English (en) > Open Language Pack for editing.

On "Filter Strings Pages" > Only Strings containing "teachers specify" > Show Strings.

![screen shot 2013-09-19 at 14 19 05](https://f.cloud.github.com/assets/1598231/1172949/20f99760-212e-11e3-9809-159e21a6af47.png)
