### ISSUE TITLE
Profile Settings 

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#67]
Change settings to disable mandatory fields.

![screen shot 2013-09-09 at 12 20 56](https://f.cloud.github.com/assets/1681436/1106361/fc8f7bea-1941-11e3-8937-b203076eaa94.png)
![screen shot 2013-09-09 at 12 21 14](https://f.cloud.github.com/assets/1681436/1106362/fe2c5dec-1941-11e3-9876-75c75d7d9001.png)

**Comment by damienh** [comment]
heyo has this been done or still being looked at?

**Comment by themarkness** [comment]
Done
