### ISSUE TITLE
We have commented user/editlib.php

### ISSUE THREAD

**Issue by oscott** [ucfalmouth/issues#68]
this is to remove unwanted 'optional' fields within the user profile edit page.

Need to do it properly before any upgrades..

**Comment by oscott** [comment]
on a side note, we can apply this patch (coming in 2.6 as core) to change some 'required' fields...

**Comment by ghost** [comment]
I reopened this as we need to make sure this is applied post upgrade

**Comment by damienh** [comment]
Now lives on list in project room for what we need to do to get to 2.5
