### ISSUE TITLE
Course Import from Linux to Windows is broken

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#7]
Two options:

1) Copy Moodle installation and database to windows dev

2) Install Moodle 2.5 on Windows and test course migration.

**Comment by damienh** [comment]
found interesting info about it in the comments here https://tracker.moodle.org/browse/MDL-37879

**Comment by damienh** [comment]
Same issue occured on my 2.4 while importing 1.x backups.. I think I could manage the problem as this way:
in the file of ...../moodle/backup/converter/moodle1/lib.php
at the line of 1216
// BACKUP RESTORE PROBLEM OCCURED BY THIS SECTION!!!
if ($sourcefullpath !== clean_param($sourcefullpath, PARAM_PATH))
{ throw new moodle1_convert_exception('file_invalid_path', $sourcefull$ }
/// END OF ERROR SECTION!!!
If you comment these 3 lines, backup restoration from 1.9 to 2.4 is completed successfully.

**Comment by themarkness** [comment]
Migration appears to work from 1.9 > 2.5 > 2.4 though Moodle warns you that it is not backwards compatible.

This has been tested using staffspace which is 2.5

**Comment by themarkness** [comment]
Issue #15 is sub issue of this

**Comment by themarkness** [comment]
Code base for learn-dev has been updated and this seems to have resolved the issue. See course uploaded here. This was bigger than 300Mb http://learn-dev.falmouth.ac.uk/course/view.php?id=240

**Comment by themarkness** [comment]
This will be fixed as part of #18
