### ISSUE TITLE
Styling in TinyMCE

### ISSUE THREAD

**Issue by etsupport** [ucfalmouth/issues#70]
Assigned to [Question #67](http://et.tenderapp.com/discussions/question/67-font-size-etc). Have tried repeating this and it does seem that you have to click twice or sometimes it doesn't change the style of text at all. 

As reported in Tender:

<blockquote><p>Hi,</p>
<p>I'm working on ENG 210 adding material to the weekly
descriptions.<br>
However, the font style seems to be erratic. I've tried to opt for
'Heading 2' - sometimes it works, sometimes it doesn't.<br>
Could you advise?</p>
<p>Many thanks</p></blockquote>

**Comment by ghost** [comment]
@etsupport It seems fine to me. You have to make sure the text is selected like so: (see below). Then, any changes are applied to the selected text. Somebody from ET should get back to whoever reported this issue and train them how to use Tiny MCE

![screen shot 2013-10-07 at 14 31 07](https://f.cloud.github.com/assets/2537947/1280549/c248e038-2f54-11e3-9ccd-36c05a15ed82.png)
