### ISSUE TITLE
Not so much of an issue but more one to keep an eye on......enrolment methods 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#71]
When learn.almouth.ac.uk was first installed the enrolment methods were changed. Since these changes were made within the site admin settings it appears that the settings have reverted back twice. 

The changes were made within the site admin settings so that any subsequent courses created would feature the correct settings for enrolment. When it was realised the enrolment methods were changed all courses had to be manually checked and amended. 

It appears that these settings have changed for a second time but am unsure as to why so it's one to keep an eye on. 

Settings have since been changed again, will keep an eye out and check periodically to make sure they haven't reverted for a 3rd time.

**Comment by themarkness** [comment]
Am closing as no action required.
