### ISSUE TITLE
Editing a section, video only displays when you refresh page *Chrome*

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#73]
http://learn.falmouth.ac.uk/course/view.php?id=196#section-1

Editing a section to include a video. Clicked save. When you return to module the video doesn't display, refreshing the page allows the video to be displayed.

**Comment by ghost** [comment]
@etsupport can somebody investigate whether this is a Moodle problem?

**Comment by ghost** [comment]
Reported issue seems to be fixed with latest theme release (Pending push to server)

**Comment by ghost** [comment]
Reopened as I managed to recreate the issue. Is temperamental.

I beleive this issue is related to: https://github.com/ucfalmouth/issues/issues/211

![screen shot 2013-10-15 at 10 27 18](https://f.cloud.github.com/assets/2537947/1332513/41fcdd52-357c-11e3-8ecc-6a1dd179d2df.png)

**Comment by Asampson** [comment]
Looks to be related to #211 as per comment above. Closing as duplicate issue.
