### ISSUE TITLE
Receive Emails as Academic Liaison Librarian 

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#74]
I am proposing we turn off recieve emails in the settings for the  Academic Liaison Librarian as they will be hit by tones as they are assigned at a system level. This naturally requires change management.

**Comment by Asampson** [comment]
This has also been requested for the role of ASK.

**Comment by themarkness** [comment]
@damienh @Asampson @oscott Have tried disabling email in role.

**Comment by damienh** [comment]
@Asampson I remember you mentioning you recreated the roles. Was the above solved as a result?

**Comment by Asampson** [comment]
Not sure which setting do you change to turn off emails all together @damienh ?

**Comment by themarkness** [comment]
Has disabling email resolved the issue?

**Comment by timosea** [comment]
I'm still getting mails for everything. Tim

On 7 Oct 2013, at 13:44, themarkness <notifications@github.com<mailto:notifications@github.com>>
 wrote:

Has disabling email resolved the issue?

—
Reply to this email directly or view it on GitHubhttps://github.com/ucfalmouth/issues/issues/74#issuecomment-25805167.

[Falmouth University] http://www.falmouth.ac.uk/      [Follow us]     [Facebook]  https://www.facebook.com/falmouthuni      [Twitter]  http://twitter.com/falmouthuni     [Youtube]  http://www.youtube.com/falmouthuniversity  [Pintrest]  http://pinterest.com/falmouthuni

  This email is confidential and intended solely for the use of the intended recipient only. If you have received this email in error, please inform us immediately and then delete it.

**Comment by Asampson** [comment]
Any news on where this setting is to turn off email? @themarkness @damienh

**Comment by themarkness** [comment]
Looks like you can only do this for particular activities. I can only see option for feedback module. Perhaps people have to manage this in their messaging settings.

**Comment by themarkness** [comment]
Will close and advise these people to change messaging settings.
