### ISSUE TITLE
Open URL - New Window vs Open

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#75]
When adding a URL as a resource it currently defaults to open in new window. This opens it in another Moodle window as opposed to an actual browser window. Is there a way of changing how this opens within admin settings? At the moment the way in which links are currently set to open isn't all that helpful as "New window".

**Comment by themarkness** [comment]
This is found in Site Admin > Activity Modules > URL > Default Display Open

**Comment by themarkness** [comment]
Done @Asampson @damienh @oscott
