### ISSUE TITLE
Print page function for module pages

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#76]
Had a questions from one of the lecturers on Film. In the old LS Anna used to be able to select print page in her browser and this would create a PDF printable copy of the LS module which students could download. When she doesn't this on the current system it also prints all the code. Is there a way of having a printable version of the module page without code?

**Comment by themarkness** [comment]
Looks like this has to be altered in CSS
http://docs.moodle.org/dev/Print_style

**Comment by Asampson** [comment]
This has been requested by Bill from Journalism also.

**Comment by Asampson** [comment]
Mark from Film has also requested for this feature.

**Comment by damienh** [comment]
@aaronmarruk Please implement print style sheet.

**Comment by ghost** [comment]
UPDATE Jan 2014: @Asampson @damienh it would be nice to know what is meant by "When she does this [prints] on the current system it also prints all the code." 

See this screenshot. "Code" is visible wherever there is a link. **Is this helpful information or not?** I'm not sure how easy / possible it is to remove the URLs as it is a "client" thing, i.e. a setting in the user's browser.

Also, the screenshot shows the intended print stylings... 

![screen shot 2014-01-07 at 11 12 37](https://f.cloud.github.com/assets/2537947/1858452/a9e3eac6-778c-11e3-84e7-96eaa4bbec77.png)

**Comment by Asampson** [comment]
![screen shot 2014-01-07 at 13 47 14](https://f.cloud.github.com/assets/1598231/1859356/4a424e62-77a2-11e3-9c49-defbd796305c.png)

Here's a screen shot when save as PDF is selected in Firefox.

**Comment by ghost** [comment]
UPDATE Jan 2014: What I am saying is anywhere there is a link – i.e. for a resource or similar – it will display the URL.

I think that this is helpful to the user, and so wouldn't mind if this "code" – as per the comments above regarding code being visible when printing screen – remained in the output for printing.

However, I have removed URLs such as breadcrumb and navigation links as these wouldn't be so helpful to the user. 

Also, to clarify, if we want to get rid of all "Code" in the print preview I would have to hide all links within the text which could lead to text being unreadable.

So I am suggesting not hiding links – either directly in the text or resources – as I believe benefits as per above can be passed onto user.

What does anyone else think?

**EDIT** 

![screen shot 2014-01-08 at 15 31 21](https://f.cloud.github.com/assets/2537947/1869410/fc04984e-7879-11e3-9e97-ef5974178294.png)

**Comment by ghost** [comment]
Closing as I'm satisfied with the results of new implemented print.css stylesheet.
