### ISSUE TITLE
My Course Terminology

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#78]
Have had some members of staff comment that the "My courses" page actually lists individual modules etc. Any chance this terminology could be changed to reflect this? I.E - My course modules or my modules?

**Comment by themarkness** [comment]
This can be done in Site Admin > language customisation

**Comment by Asampson** [comment]
Site Admin > Language Customisation > Select English (en) > Open Language Pack for editing. 

On "Filter Strings Pages" > Only Strings containing "My Courses" > Show Strings. 

![screen shot 2013-09-19 at 10 41 13](https://f.cloud.github.com/assets/1598231/1171811/c2d18738-210f-11e3-880a-d5034b86fe60.png)
