### ISSUE TITLE
Resource Center IA (Information Architecture) "Tag Cloud Deluxe"

### ISSUE THREAD

**Issue by ghost** [ucfalmouth/issues#79]
Use a "free-tagging" system to allow users to tag content.

Build a dynamic set of navigation based on submitted user tags. This could allow for the organisation of content based on user input, thus getting around the problem of complex resources IA.

Resulting navigation would be based on how users search for things / tag things.

**Comment by damienh** [comment]
@aaronmarruk This now needs to become a presentation with the aim of taking it to DIG. This will be delivered within the team first as part of our meetings.
