### ISSUE TITLE
Return to main course page.... removed?

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#80]
Just testing my student user account to check what students see. In this screen shot I am on the introduction section. At the top is the "Return to main course page" option. As a student I wouldn't know what this did and gets a bit confused with the actual course page. Could this be taken off in anyway? 

![screen shot 2013-09-18 at 15 42 36](https://f.cloud.github.com/assets/1598231/1165698/a0301356-2070-11e3-8453-7408088a0b69.png)

**Comment by ghost** [comment]
This will be fixed with the next theme update.

**Comment by Asampson** [comment]
Is there any way of hiding it in the meantime? I really think this has the potential to confuse people especially with the different terminology and I think we'd probably get comments on this right away.

**Comment by ghost** [comment]
No point. We are pushing the theme this afternoon.
