### ISSUE TITLE
Terminology: Teachers changed to staff/academics

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#82]
Several references to teachers currently exist in the Learning Space. Should these be changed to staff/academics?

**Comment by themarkness** [comment]
@Asampson Can you give examples, is it a DB query.

**Comment by Asampson** [comment]
It's a terminology setting within Moodle. Just needed change management.

**Comment by Asampson** [comment]
Still needing CM on this. Example below: 
![screen shot 2013-10-07 at 14 42 30](https://f.cloud.github.com/assets/1598231/1280620/5e3c8e76-2f56-11e3-8895-ca70747a9e17.png)

**Comment by Asampson** [comment]
Make it you (more personal). @oscott Amy and @damienh

**Comment by themarkness** [comment]
Searched for teacher in language pack and replaced with "you"
