### ISSUE TITLE
Unknown Action - Posting to forum 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#83]
When posting to a forum or replying to a discussion you hit post to forum. You then hit back to module to return to the module page, this presents an error; "Unknown Action".

Something to do with this: http://learn.falmouth.ac.uk/mod/forum/post.php

**Comment by Asampson** [comment]
Update: Have had some students complaining about this issue to, can it please be escalated? Thank you, Amy

**Comment by ghost** [comment]
This has now been resolved. Pending theme update.

Just so you know, we'll be updating the theme A-LOT during these bug fixes. So if you don't see the changes, assume the update is happening in the immediate future.

Thanks!
