### ISSUE TITLE
Terminology - Courses to Modules

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#85]
Can we please change terminology on the front page to modules, from courses. 

![screen shot 2013-09-20 at 09 44 18](https://f.cloud.github.com/assets/1598231/1179668/569cfdfe-21dc-11e3-8032-aa39c6ddf554.png)

**Comment by oscott** [comment]
Hi @Asampson, is this now done?

**Comment by Asampson** [comment]
Yes...sorry forgot to close!
