### ISSUE TITLE
Add menu item missing

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#86]
Need to be able to add menu item to the section 0 sideblock navigation. 
![screen shot 2013-09-20 at 10 58 07](https://f.cloud.github.com/assets/1598231/1179676/a1591aee-21dc-11e3-8e90-6595636f8d67.png)

**Comment by ghost** [comment]
This has now been resolved.

**Comment by Asampson** [comment]
Still can't see it. 
![screen shot 2013-09-21 at 13 15 32](https://f.cloud.github.com/assets/1598231/1185597/7ee16a3a-22b7-11e3-8b4f-265e89648816.png)

**Comment by ghost** [comment]
Pending theme update.
