### ISSUE TITLE
My Courses Link Showing up in Section Menu 

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#87]
![screen shot 2013-09-20 at 11 19 44](https://f.cloud.github.com/assets/1598231/1179738/2a4f0dc6-21de-11e3-87eb-1ce0933802a6.png)

This is currently happening on some of the menu blocks. This can be manually changed by going into the menu settings. 

![screen shot 2013-09-20 at 11 20 49](https://f.cloud.github.com/assets/1598231/1179747/566337d4-21de-11e3-9ce5-02799f95f1cf.png)

**Comment by oscott** [comment]
@Asampson - Go for it, sounds fine to me, can you just check that the stuff on the front page and the breadcrumb don't seem to be affected once its done - looks very undoable.

**Comment by Asampson** [comment]
@oscott Have now changed it in the site default settings. Site Admin > Plug ins > Blocks > Course Menu 

Although this changes the default it doesn't change the ones already created. So any that we see will have to be manually configured in the individual module page settings.
