### ISSUE TITLE
Old Menus in old LS are linking to new LS

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#89]
When visiting the archive site staff are unable to navigate as the old menus are hard coded. Turning off themes maybe a solution?

**Comment by damienh** [comment]
I believe that this is old menus in the theme? As the front page menu nav has been changed.

**Comment by oscott** [comment]
I guess we should have done this when we did the db replace and frontpage one...

We can either find & replace in the theme folder on a local copy and then apply, OR could we not set them all to a default theme and people can use the Moodle nav.

I guess that's asking for trouble...

Shall we try the find and replace?

**Comment by damienh** [comment]
@oscott whats the best way to do a bulk find and replace over a list of folders. I could download the entire theme directory for TLS10 and do find and replace just cant work out the best way,

**Comment by Asampson** [comment]
Still getting issues with this. Having to direct staff to keep using the breadcrumbs, if we can do a find and replace that would be great. Staff are getting a bit frustrated.

**Comment by oscott** [comment]
.

**Comment by damienh** [comment]
@oscott did find and replace for all files
