### ISSUE TITLE
Via Tender: Assign System Role for Vicky Weavers on StaffSpace and Learning Space

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#9]
Assigned to [Help #15](http://et.tenderapp.com/discussions/help/15-assign-system-role-for-vicky-weavers-on-staffspace-and-learning-space). As reported in Tender:

<blockquote><p>Vicky needs to be made a Content Administrator and this will be
done site wide until both systems are moved into production.</p></blockquote>

**Comment by oscott** [comment]
Agreed that this is fine for now and that we will need a training role post move (Training Allowing appropriate changes in the future) - this will be separated from the current solution which is to give teacher role across all courses. [@themarkness @oscott @patrick-et]
