### ISSUE TITLE
Text Editor Window is VERY tiny

### ISSUE THREAD

**Issue by damienh** [ucfalmouth/issues#96]
Hi Aaron,

Not sure if this is part of your new theme update or a bug but the text editor window has gone very small and cant really be used unless dragged bigger. 

Damien

**Comment by themarkness** [comment]
Works most of the time for me, but sometimes defaults to one line. Can still drag expand window though.

**Comment by ghost** [comment]
As always, a URL is necessary for me to solve this.

As Mark has pointed out, it only occurs on certain pages? Or is the problem inconsistent, i.e. sometimes the text editor is displayed correctly, and sometimes it isn't. What pages are you viewing when it breaks etc...

Screen grabs and a URL would really help.

Cheers.

**Comment by damienh** [comment]
Hey @aaronmarruk link is here http://learningspace.falmouth.ac.uk/course/modedit.php?update=64&return=0&sr=0 and screenshot is attached 
![capture](https://f.cloud.github.com/assets/810107/1190686/170caeda-243b-11e3-9857-e8e78fedadb1.png)

**Comment by ghost** [comment]
Cheers, that is much more helpful.

**Comment by ghost** [comment]
This has now been resolved. Pending theme update.
