### ISSUE TITLE
Course Finder not working in IE

### ISSUE THREAD

**Issue by themarkness** [ucfalmouth/issues#98]
Can type in search box but it does not populate results.

**Comment by ghost** [comment]
Hi Mark,

which version of IE? Also, are you viewing in compatibility mode?

Cheers.

**Comment by themarkness** [comment]
IE 9 on Windows 7.

I can't recreate this in Browserstack though using compatibility mode or otherwise, could be specific to the machine/image.

**Comment by ghost** [comment]
All seems ok with the functionality of the course finder in IE.
