### ISSUE TITLE
New Role needed for those who have been trained

### ISSUE THREAD

**Issue by Asampson** [ucfalmouth/issues#99]
Think we need a new role within the training area for Vicky to subscribe anyone who has been trained. At the moment the academic role is being used, however when individuals create assignments/forum posts and forget to turn off notifications anyone who has the academic role in this area is being sent an email.

**Comment by Asampson** [comment]
Going to create new training role, turn off emails for this role. Move current academic users so we still have a record of anyone who has been trained. 

CM Approved - @Patrick-ET @damienh Amy

**Comment by damienh** [comment]
We also need to ideally rethink how they are enrolled or how records are kept. I noticed a member of staff who completed the training still has T1 ect courses in their My Courses block. This becomes a massive list once they are given academic access to their course.

**Comment by themarkness** [comment]
Perhaps those who have been trained should be Unenrolled from the training category afterwards and just keep training info on who was done it in a spreadsheet until we have CRM.

**Comment by Asampson** [comment]
Staff who were enrolled have since been unenrolled from the training category and a record kept within the training area of G docs.
